const catalog=window.NUGU_PLATFORM_CATALOG||{};
const config=window.NUGU_CONFIG||{};
let payload=window.NUGU_FALLBACK||{artists:[],rankState:{liveCount:0,totalCount:0,minSnapshots:2},collectors:[]};
let artists=[];
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=n=>Number.isFinite(Number(n))?new Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(Number(n)):'—';
const pct=n=>Number.isFinite(Number(n))?`${Number(n)>=0?'+':''}${(Number(n)*100).toFixed(Math.abs(Number(n))<.01?1:0)}%`:'—';
const dateLabel=d=>!d?'Ongoing':new Intl.DateTimeFormat('en',{year:'numeric',month:'short',day:'numeric'}).format(new Date(d.length===10?`${d}T00:00:00Z`:d));
const platformLabel=id=>catalog[id]?.label||id;
const platformBadge=id=>`<span class="platform-badge platform-${esc(id)}">${esc(platformLabel(id))}</span>`;
const byPlatform=(a,id)=>a.metrics?.find(x=>x.platform===id)?.metrics||null;
const rankReason=r=>r?.metric?`${platformLabel(r.platform)} ${esc(r.metric)} ${pct(r.delta)}`:`${platformLabel(r?.platform)} ${pct(r?.delta)}`;
function normalize(raw){return (raw||[]).map(a=>({...a,members:Array.isArray(a.members)?a.members:[],platforms:Array.isArray(a.platforms)?a.platforms:[],metrics:Array.isArray(a.metrics)?a.metrics:[],content:Array.isArray(a.content)?a.content:[],reasons:Array.isArray(a.reasons)?a.reasons:[]}));}
function renderRibbon(){const ids=['youtube','instagram','x','lastfm','tiktok','spotify','wikidata','musicbrainz','commons'];$('#platformRibbon').innerHTML=ids.map(id=>{const p=catalog[id];return `<span class="ribbon-item"><b>${esc(p.label)}</b><small>${esc(p.tier)} · ${esc(p.cadence)}</small></span>`}).join('');}
function renderRankState(){const s=payload.rankState||{}; const live=Number(s.liveCount||0); const total=Number(s.totalCount||artists.length);$('#rankState').innerHTML=live?`<span class="verified-pill">LIVE</span><b>${live} ranked / ${total} tracked</b><small>Latest real snapshot deltas only</small>`:`<span class="warm-pill">DATA WARM-UP</span><b>Waiting for ${s.minSnapshots||2} snapshots</b><small>The site stays unranked until real deltas exist.</small>`;}
function rankMarkup(a){if(a.rank!=null&&a.score!=null){const top=a.reasons?.[0];return `<span class="verified-pill">#${esc(a.rank)} · ${esc(a.score)}</span><span>${Math.round(Number(a.coverage||0)*100)}% coverage${top?` · ${esc(rankReason(top))}`:''}</span>`}return `<span class="warm-pill">WARMING</span><span>${a.platforms.length} verified endpoints</span>`;}
function renderGrid(){$('#artistGrid').innerHTML=artists.map((a,i)=>`<article class="artist-card" data-slug="${esc(a.slug)}" tabindex="0"><img src="${esc(a.image_url)}" alt="${esc(a.name)} group photo" loading="lazy" referrerpolicy="no-referrer"/><div class="card-top"><span class="index-no">${String(a.rank||i+1).padStart(2,'0')}</span><span class="check">✓</span></div><div class="card-bottom"><div class="card-rankline">${rankMarkup(a)}</div><h3>${esc(a.name)}</h3><div class="artist-kor">${esc(a.korean_name||'')}</div><div class="card-facts"><span>${esc(a.group_type||'K-pop Group')}</span><span>${a.debut_date?`Debut ${esc(a.debut_date.slice(0,4))}`:'Debut verified'}</span><span>${a.members.length?`${a.members.length} members`:'members pending'}</span></div><div class="mini-platforms">${a.platforms.slice(0,6).map(p=>platformBadge(p.platform)).join('')}</div></div></article>`).join('');$$('.artist-card').forEach(el=>{el.onclick=()=>openArtist(el.dataset.slug);el.onkeydown=e=>{if(e.key==='Enter')openArtist(el.dataset.slug)}});}
function allContent(){return artists.flatMap(a=>a.content.map(c=>({...c,artist:a}))).sort((a,b)=>Date.parse(b.published_at||0)-Date.parse(a.published_at||0));}
function renderFeed(filter='all'){const rows=allContent().filter(c=>filter==='all'||c.platform===filter);$('#fandomFeed').innerHTML=rows.map(c=>`<a class="feed-card" href="${esc(c.content_url)}" target="_blank" rel="noopener"><div class="feed-thumb">${c.thumbnail_url?`<img src="${esc(c.thumbnail_url)}" alt="${esc(c.title)} thumbnail" loading="lazy">`:`<div class="text-thumb">${esc(platformLabel(c.platform))}</div>`}<span class="feed-platform">${platformBadge(c.platform)}</span></div><div class="feed-copy"><small>${esc(c.artist.name)} · ${esc(c.kind||'Official content')}</small><h3>${esc(c.title)}</h3><p>${esc(c.channel_name||c.artist.name)} · ${dateLabel(c.published_at)}${c.public_metrics?.views!=null?` · ${fmt(c.public_metrics.views)} views`:''}</p><em>✓ ${esc(c.verification_rule||'Verified canonical source')}</em></div></a>`).join('')||'<p class="empty">No verified content for this filter.</p>';}
function renderFeedFilters(){const used=['all',...new Set(allContent().map(x=>x.platform))];$('#feedFilters').innerHTML=used.map((id,i)=>`<button class="feed-filter ${i===0?'active':''}" data-feed="${esc(id)}">${id==='all'?'All':esc(platformLabel(id))}</button>`).join('');$$('.feed-filter').forEach(b=>b.onclick=()=>{$$('.feed-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderFeed(b.dataset.feed)})}
function collectorState(id){const c=(payload.collectors||[]).find(x=>x.platform===id);if(!c)return null;return c.status==='success'?'READY':String(c.status||'UNKNOWN').toUpperCase()}
function renderConnectors(){const ids=['youtube','instagram','x','lastfm','tiktok','spotify','wikidata','musicbrainz','commons','weverse','mnetplus','bstage'];$('#connectorBoard').innerHTML=ids.map(id=>{const p=catalog[id];const state=collectorState(id)||(p.rank?'WARMING':p.tier);const ready=state==='READY'||['DISPLAY','IDENTITY','MEDIA','OFFICIAL','LINK'].includes(state);return `<div class="connector-row"><div>${platformBadge(id)}<b>${esc(p.label)}</b></div><div><small>${esc(p.mode)}</small><strong>${esc(p.cadence)}</strong></div><span class="connector-status ${ready?'ready':'gated'}">${esc(state)}</span></div>`}).join('');}
function metricCards(a){const rows=[]; const y=byPlatform(a,'youtube'),ig=byPlatform(a,'instagram'),x=byPlatform(a,'x'),lf=byPlatform(a,'lastfm');if(y) rows.push(['YouTube',fmt(y.subscribers),'subscribers']);if(ig) rows.push(['Instagram',fmt(ig.followers),'followers']);if(x) rows.push(['X',fmt(x.followers),'followers']);if(lf) rows.push(['Last.fm',fmt(lf.listeners),'listeners']);if(a.score!=null) rows.unshift(['Momentum',String(a.score),`#${a.rank} · ${Math.round(Number(a.coverage||0)*100)}% coverage`]);if(!rows.length) rows.push(['Signal','Warming','real snapshots pending']);return rows.slice(0,4).map(([k,v,s])=>`<div class="metric"><small>${esc(k)}</small><strong>${esc(v)}</strong><span>${esc(s)}</span></div>`).join('');}
function openArtist(slug){
  const a=artists.find(x=>x.slug===slug);if(!a)return;const platforms=a.platforms||[];
  const reasons=a.reasons?.length?`<section class="detail-section"><div class="detail-section-head"><h3>Why they are moving</h3><span>real deltas</span></div><div class="official-network">${a.reasons.map(r=>`<div><b>${esc(platformLabel(r.platform))}</b><small>${esc(r.metric||'signal')} · ${esc(pct(r.delta))}</small></div>`).join('')}</div></section>`:'';
  $('#dialogBody').innerHTML=`<div class="detail-hero"><img src="${esc(a.image_url)}" alt="${esc(a.name)} verified group image"/><div class="detail-title"><span class="verified-pill">✓ VERIFIED ENTITY</span><h2>${esc(a.name)}</h2><div>${esc(a.korean_name||'')} · ${esc(a.group_type||'K-pop Group')}</div></div></div><div class="detail-body"><div class="detail-grid">${metricCards(a)}</div>${reasons}<section class="detail-section"><div class="detail-section-head"><h3>Official network</h3><span>${platforms.length} verified</span></div><div class="official-network">${platforms.map(p=>`<a href="${esc(p.account_url)}" target="_blank" rel="noopener">${platformBadge(p.platform)}<b>${esc(p.handle||platformLabel(p.platform))}</b><small>✓ ${esc(p.verified_by||'verified source')}</small></a>`).join('')}</div></section><section class="detail-section"><div class="detail-section-head"><h3>Verified videos & posts</h3><span>${a.content.length} items</span></div><div class="video-list">${a.content.map(c=>`<a class="video-row" href="${esc(c.content_url)}" target="_blank" rel="noopener">${c.thumbnail_url?`<img src="${esc(c.thumbnail_url)}" alt="${esc(c.title)} thumbnail" loading="lazy">`:`<div class="video-placeholder">${esc(platformLabel(c.platform))}</div>`}<div class="video-copy">${platformBadge(c.platform)}<b>${esc(c.title)}</b><small>${esc(c.channel_name||a.name)} · ${dateLabel(c.published_at)}${c.public_metrics?.views!=null?` · ${fmt(c.public_metrics.views)} views`:''}</small><em>✓ ${esc(c.verification_rule||'verified canonical source')}</em></div><span class="play-chip">↗</span></a>`).join('')||'<p class="license-note">No verified content yet. We leave it empty instead of guessing.</p>'}</div></section><section class="detail-section"><h3>Members</h3><div class="member-list">${a.members.length?a.members.map(x=>`<span>${esc(x)}</span>`).join(''):'<span>Verified member data pending</span>'}</div></section><section class="detail-section"><h3>Canonical identity</h3><p class="license-note">Wikidata: <b>${esc(a.qid||'—')}</b><br>MusicBrainz: <b>${esc(a.mbid||'—')}</b>${a.spotify_id?`<br>Spotify: <b>${esc(a.spotify_id)}</b>`:''}<br>Official: <a href="${esc(a.official_url||'#')}" target="_blank" rel="noopener">${esc(a.official_url||'—')}</a></p></section><section class="detail-section"><h3>Image provenance</h3><p class="license-note"><b>${esc(a.image_license||'license pending')}</b> · ${esc(a.image_credit||'')}</p>${a.image_page_url?`<a href="${esc(a.image_page_url)}" target="_blank" rel="noopener">Open source file ↗</a>`:''}</section></div>`;
  $('#artistDialog').showModal();
}
function hero(){const a=artists.find(x=>x.rank===1)||artists[0];if(!a)return;$('#heroMedia').style.backgroundImage=`url("${String(a.image_url).replace(/"/g,'')}")`;$('#heroProof').innerHTML=`<div class="proof-name"><strong>${esc(a.name)}</strong>${a.rank?`<span class="verified-pill">#${esc(a.rank)} · ${esc(a.score)}</span>`:`<span class="warm-pill">VERIFIED · WARMING</span>`}</div><div class="proof-meta">${esc(a.korean_name||'')} · ${a.members.length?`${a.members.length} members · `:''}${esc(a.agency||'Agency verified')}</div><div class="proof-sources">${a.platforms.slice(0,6).map(p=>`<span>${esc(platformLabel(p.platform))}</span>`).join('')}</div>`}
function renderSearch(q){const s=q.trim().toLowerCase(),rows=artists.filter(a=>!s||[a.name,a.korean_name,a.agency,...a.members].join(' ').toLowerCase().includes(s));$('#searchResults').innerHTML=rows.map(a=>`<div class="search-result" data-slug="${esc(a.slug)}"><img src="${esc(a.image_url)}" alt=""><div><b>${esc(a.name)}</b><small>${esc(a.korean_name||'')} · ${a.platforms.length} verified endpoints${a.rank?` · #${a.rank}`:''}</small></div></div>`).join('')||'<div class="search-result"><div>No verified artist found.</div></div>';$$('.search-result[data-slug]').forEach(r=>r.onclick=()=>{$('#searchOverlay').hidden=true;openArtist(r.dataset.slug)})}
function wire(){$('#closeDialog').onclick=()=>$('#artistDialog').close();$('#exploreBtn').onclick=()=>$('#radar').scrollIntoView({behavior:'smooth'});$('#searchButton').onclick=()=>{$('#searchOverlay').hidden=false;$('#searchInput').value='';renderSearch('');setTimeout(()=>$('#searchInput').focus(),10)};$('#searchClose').onclick=()=>$('#searchOverlay').hidden=true;$('#searchInput').oninput=e=>renderSearch(e.target.value);$('#searchOverlay').onclick=e=>{if(e.target===$('#searchOverlay'))$('#searchOverlay').hidden=true};document.addEventListener('keydown',e=>{if(e.key==='/'&&$('#searchOverlay').hidden){e.preventDefault();$('#searchButton').click()}else if(e.key==='Escape'&&!$('#searchOverlay').hidden)$('#searchOverlay').hidden=true});}
function render(){artists=normalize(payload.artists);$('#versionLabel').textContent=config.build||payload.build||'Updated 2026.09.05';hero();renderRibbon();renderRankState();renderGrid();renderFeedFilters();renderFeed();renderConnectors();}
async function boot(){wire(); render();const base=String(config.apiBase||'').replace(/\/$/,''); if(!base)return;try{const r=await fetch(`${base}/api/v1/home`,{headers:{Accept:'application/json'},cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);payload=await r.json();render();document.documentElement.dataset.live='true';}catch(e){console.warn('NUGU RADAR API unavailable; showing verified seed fallback.',e);document.documentElement.dataset.live='false';}}
boot();
