const cfg=window.NUGU_CONFIG||{};const api=String(cfg.apiBase||'').replace(/\/$/,'');
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtTime=s=>{const n=Math.max(0,Number(s||0));if(n<60)return`${n}s`;const m=Math.floor(n/60);if(m<60)return`${m}m`;const h=Math.floor(m/60),rm=m%60;return`${h}h ${rm}m`};
const fmt=n=>Number.isFinite(Number(n))?new Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(Number(n)):'—';
function visitor(){const a=window.NUGU_AUTH?.getIdentitySync?.();if(a)return{id:a.visitorId,name:a.displayName||localStorage.getItem('nuguCommentName')||'',authenticated:!!a.authenticated};let id=localStorage.getItem('nuguVisitorId');if(!id){id=(crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`).replace(/[^A-Za-z0-9_-]/g,'');localStorage.setItem('nuguVisitorId',id)}return{id,name:localStorage.getItem('nuguCommentName')||'',authenticated:false}}
function ensureName(){const p=visitor();if(p.name&&p.name.length>=2)return p.name;if(p.authenticated)return'Radar fan';const name=(prompt('Pick a nickname for NUGU RADAR')||'').trim().slice(0,20);if(name.length<2)return null;window.NUGU_AUTH?.setDisplayName?.(name)||localStorage.setItem('nuguCommentName',name);return name}
async function requireLogin(message='커뮤니티 참여는 로그인 후 가능해요.'){let identity=null;try{identity=await window.NUGU_AUTH?.getIdentity?.()}catch{}if(identity?.authenticated&&identity.accessToken)return identity;alert(message);window.NUGU_AUTH_UI?.signIn?.(location.href);return null}
let me={wallet:{earned:0,spent:0,balance:0},picks:[]};
function isPicked(slug){return me.picks?.some(x=>x.slug===slug)}
async function getJson(url,opts={}){let identity=null;try{identity=await window.NUGU_AUTH?.getIdentity?.()}catch(e){console.warn('auth session refresh failed',e)}const auth=window.NUGU_AUTH?.authHeaders?.(identity)||{};const r=await fetch(url,{...opts,headers:{Accept:'application/json',...auth,...(opts.headers||{})},cache:'no-store'});const data=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(data.error||`HTTP ${r.status}`),{code:data.error,data,status:r.status});return data}
function walletRender(){const w=me.wallet||{},p=visitor();$('#walletCard').innerHTML=`<small>YOUR RADAR TIME</small><strong>${fmtTime(w.balance)}</strong><span>${p.authenticated?`${fmtTime(w.earned)} earned · ${fmtTime(w.spent)} spent · synced to your account`:'보기는 누구나 · 참여/저장은 로그인 후 가능'}</span>`}
function roomHref(slug){return `room.html?artist=${encodeURIComponent(slug)}`}
function myCard(a){const outside=a.radar_eligible===false;return `<article class="community-card" data-slug="${esc(a.slug)}">${a.image_url?`<img src="${esc(a.image_url)}" alt="${esc(a.name)}" loading="lazy" referrerpolicy="no-referrer">`:''}<div class="community-card-copy"><small>${a.picked_at?`Picked ${new Date(a.picked_at).toLocaleDateString()}`:'Picked'}${a.discovered_rank?` · found at #${esc(a.discovered_rank)}`:''}</small><h3>${esc(a.name)}</h3><p>${outside?`OUTSIDE RADAR · ${esc(a.radar_tier||'mainstream')}`:`${esc(a.activity_state||'verified')} · ${a.rank?`now #${esc(a.rank)} momentum`:'momentum warming'}`}</p><div class="community-card-actions"><a href="${roomHref(a.slug)}">${outside?'추억 아지트 보기':'아지트 들어가기 ♡'}</a><button class="secondary" data-unpick="${esc(a.slug)}">Unpick</button></div></div></article>`}
function renderMe(){walletRender();const root=$('#myRadar'),p=visitor();if(!p.authenticated){root.innerHTML='<div class="empty-community">아지트는 자유롭게 둘러볼 수 있어요. <button type="button" id="communityLogin">로그인하고 Pick·수다·같이보기 시작하기</button></div>';$('#communityLogin')?.addEventListener('click',()=>window.NUGU_AUTH_UI?.signIn?.(location.href));return}root.innerHTML=me.picks?.length?me.picks.map(myCard).join(''):`<div class="empty-community">아직 Pick한 팀이 없어요. 아래에서 최대 세 팀까지 골라봐요.</div>`;root.querySelectorAll('[data-unpick]').forEach(b=>b.onclick=()=>setPick(b.dataset.unpick,false))}
async function loadMe(){if(!api)return;const p=visitor();if(!p.authenticated){me={wallet:{earned:0,spent:0,balance:0},picks:[]};renderMe();return}try{me=await getJson(`${api}/api/v1/community/me?visitorId=${encodeURIComponent(p.id)}`);renderMe()}catch(e){console.warn(e);me={wallet:{earned:0,spent:0,balance:0},picks:[]};renderMe()}}
async function setPick(slug,active=true){const identity=await requireLogin('Pick과 아지트 참여는 로그인 후 가능해요.');if(!identity)return;const p=visitor(),name=p.name||'Radar fan';try{const data=await getJson(`${api}/api/v1/community/pick/${encodeURIComponent(slug)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({visitorId:p.id,displayName:name,active})});me={wallet:data.wallet,picks:data.picks};renderMe();await loadSpotlight();if(active)location.href=roomHref(slug)}catch(e){alert(e.code==='outside_radar'?'That act has crossed the NUGU RADAR mainstream gate.':e.code==='pick_limit'?'You can keep up to three active picks. Unpick one first.':e.code==='sign_in_required'||e.status===401?'다시 로그인해줘.':'Could not update My Radar.') }}
function searchCard(a){const picked=isPicked(a.slug),outside=a.radar_eligible===false;return `<article class="spotlight-card"><img src="${esc(a.image_url||'')}" alt="${esc(a.name)}" loading="lazy" referrerpolicy="no-referrer"><div><h3>${esc(a.name)}</h3><p>${esc(a.korean_name||'')} ${a.agency?`· ${esc(a.agency)}`:''}${outside?` · OUTSIDE RADAR`:(a.rank?` · #${esc(a.rank)}`:'')}</p></div><div class="community-card-actions">${outside?`<span class="verified-pill">${esc(a.radar_tier||'mainstream')}</span>`:picked?`<a href="${roomHref(a.slug)}">아지트</a>`:`<button data-pick="${esc(a.slug)}">Pick</button>`}</div></article>`}
async function searchArtists(q){const root=$('#artistSearchResults');root.innerHTML='<div class="empty-community">Searching verified catalog…</div>';try{const data=await getJson(`${api}/api/v1/search?q=${encodeURIComponent(q)}`);root.innerHTML=data.items?.length?data.items.map(searchCard).join(''):`<div class="empty-community">No verified artist matched that search.</div>`;root.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>setPick(b.dataset.pick,true))}catch(e){root.innerHTML='<div class="empty-community">Search is unavailable right now.</div>'}}
function spotlightCard(a,i){return `<a class="spotlight-card" href="${roomHref(a.slug)}"><img src="${esc(a.image_url||'')}" alt="${esc(a.name)}" loading="lazy" referrerpolicy="no-referrer"><div><h3>${String(i+1).padStart(2,'0')} · ${esc(a.name)}</h3><p>${fmtTime(a.glow_24h_seconds)} lit in 24h · ${fmt(a.supporters)} supporters</p></div><div class="spotlight-score"><b>${fmt(Number(a.community_glow_score||0))}</b><span>GLOW SCORE</span></div></a>`}
async function loadSpotlight(){const root=$('#spotlightGrid');try{const data=await getJson(`${api}/api/v1/community/spotlight`);root.innerHTML=data.items?.length?data.items.map(spotlightCard).join(''):`<div class="empty-community">No Community Glow yet. The first eligible room to spend Radar Time takes the first spotlight.</div>`}catch(e){root.innerHTML='<div class="empty-community">Community Spotlight is warming up.</div>'}}

let fanRankMetric='overall';
const fanRankCopy={
  overall:{label:'종합 덕질 온도',detail:a=>`${fmt(a.unique_fans)}명 · 활동 ${fmt(a.total_actions)}개`,score:a=>Number(a.overall_score||0)},
  topkku:{label:'탑꾸',detail:a=>`${fmt(a.topkku_fans)}명이 ${fmt(a.topkku_count)}장 꾸밈`,score:a=>Number(a.topkku_score||0)},
  hideout:{label:'아지트 수다',detail:a=>`${fmt(a.hideout_fans)}명 · 수다 ${fmt(a.hideout_actions)}개`,score:a=>Number(a.hideout_score||0)},
  watch:{label:'같이보기',detail:a=>`${fmt(a.watch_fans)}명 · 반응 ${fmt(a.watch_actions)}개`,score:a=>Number(a.watch_score||0)}
};
function fanRankCard(a,i){const m=fanRankCopy[fanRankMetric]||fanRankCopy.overall;return `<a class="fan-rank-card ${i<3?'top-three':''}" href="${roomHref(a.slug)}"><div class="fan-rank-place">${i+1}</div><img src="${esc(a.image_url||'')}" alt="${esc(a.name)}" loading="lazy" referrerpolicy="no-referrer"><div class="fan-rank-copy"><h3>${esc(a.name)}</h3><p>${esc(m.detail(a))}</p><strong>${esc(m.label)} · ${fmt(m.score(a))}</strong></div>${i===0?'<span class="rank-doodle">이번 주 여기 난리남 ♡</span>':''}</a>`}
async function loadFanRanking(metric=fanRankMetric){fanRankMetric=metric;const root=$('#fanRankGrid');if(!root)return;root.innerHTML='<div class="fan-rank-empty">이번 주 아지트 온도 재는 중…</div>';try{const data=await getJson(`${api}/api/v1/community/fan-ranking?metric=${encodeURIComponent(metric)}&limit=10`);root.innerHTML=data.items?.length?data.items.map(fanRankCard).join(''):'<div class="fan-rank-empty">이번 주 기록이 아직 충분히 쌓이지 않았어요. 첫 불씨를 붙여줘 ♡</div>'}catch(e){console.warn(e);root.innerHTML='<div class="fan-rank-empty">덕질 온도를 잠시 불러오지 못했어요.</div>'}}
document.querySelectorAll('#fanRankTabs [data-rank-metric]').forEach(b=>b.onclick=()=>{document.querySelectorAll('#fanRankTabs [data-rank-metric]').forEach(x=>x.classList.toggle('active',x===b));loadFanRanking(b.dataset.rankMetric)});
$('#artistSearch').onsubmit=e=>{e.preventDefault();const q=$('#artistSearchInput').value.trim();if(q)searchArtists(q)};
window.addEventListener('nugu-auth-changed',()=>loadMe());
$('#versionLabel').textContent=cfg.build||'Updated 2026.09.12';renderMe();loadMe();loadSpotlight();loadFanRanking();