const cfg=window.NUGU_CONFIG||{};const api=String(cfg.apiBase||'').replace(/\/$/,'');
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtTime=s=>{const n=Math.max(0,Number(s||0));if(n<60)return`${n}s`;const m=Math.floor(n/60);if(m<60)return`${m}m`;const h=Math.floor(m/60),rm=m%60;return`${h}h ${rm}m`};
const fmt=n=>Number.isFinite(Number(n))?new Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(Number(n)):'—';
function visitor(){const a=window.NUGU_AUTH?.getIdentitySync?.();if(a)return{id:a.visitorId,name:a.displayName||localStorage.getItem('nuguCommentName')||'',authenticated:!!a.authenticated};let id=localStorage.getItem('nuguVisitorId');if(!id){id=(crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`).replace(/[^A-Za-z0-9_-]/g,'');localStorage.setItem('nuguVisitorId',id)}return{id,name:localStorage.getItem('nuguCommentName')||'',authenticated:false}}
function ensureName(){const p=visitor();if(p.name&&p.name.length>=2)return p.name;if(p.authenticated)return'Radar fan';const name=(prompt('Pick a nickname for NUGU RADAR')||'').trim().slice(0,20);if(name.length<2)return null;window.NUGU_AUTH?.setDisplayName?.(name)||localStorage.setItem('nuguCommentName',name);return name}
let me={wallet:{earned:0,spent:0,balance:0},picks:[]};
function isPicked(slug){return me.picks?.some(x=>x.slug===slug)}
async function getJson(url,opts={}){let identity=null;try{identity=await window.NUGU_AUTH?.getIdentity?.()}catch(e){console.warn('auth session refresh failed',e)}const auth=window.NUGU_AUTH?.authHeaders?.(identity)||{};const r=await fetch(url,{...opts,headers:{Accept:'application/json',...auth,...(opts.headers||{})},cache:'no-store'});const data=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(data.error||`HTTP ${r.status}`),{code:data.error,data,status:r.status});return data}
function walletRender(){const w=me.wallet||{},p=visitor();$('#walletCard').innerHTML=`<small>YOUR RADAR TIME</small><strong>${fmtTime(w.balance)}</strong><span>${fmtTime(w.earned)} earned · ${fmtTime(w.spent)} spent${p.authenticated?' · synced to your account':' · sign in to sync across devices'}</span>`}
function roomHref(slug){return `room.html?artist=${encodeURIComponent(slug)}`}
function myCard(a){const outside=a.radar_eligible===false;return `<article class="community-card" data-slug="${esc(a.slug)}">${a.image_url?`<img src="${esc(a.image_url)}" alt="${esc(a.name)}" loading="lazy" referrerpolicy="no-referrer">`:''}<div class="community-card-copy"><small>${a.picked_at?`Picked ${new Date(a.picked_at).toLocaleDateString()}`:'Picked'}${a.discovered_rank?` · found at #${esc(a.discovered_rank)}`:''}</small><h3>${esc(a.name)}</h3><p>${outside?`OUTSIDE RADAR · ${esc(a.radar_tier||'mainstream')}`:`${esc(a.activity_state||'verified')} · ${a.rank?`now #${esc(a.rank)} momentum`:'momentum warming'}`}</p><div class="community-card-actions"><a href="${roomHref(a.slug)}">${outside?'View archived room':'Enter Radar Room'}</a><button class="secondary" data-unpick="${esc(a.slug)}">Unpick</button></div></div></article>`}
function renderMe(){walletRender();const root=$('#myRadar');root.innerHTML=me.picks?.length?me.picks.map(myCard).join(''):`<div class="empty-community">No picks yet. Search below and claim up to three acts.</div>`;root.querySelectorAll('[data-unpick]').forEach(b=>b.onclick=()=>setPick(b.dataset.unpick,false))}
async function loadMe(){if(!api)return;const p=visitor();try{me=await getJson(`${api}/api/v1/community/me?visitorId=${encodeURIComponent(p.id)}`);renderMe()}catch(e){console.warn(e);renderMe()}}
async function setPick(slug,active=true){const name=ensureName();if(!name)return;const p=visitor();try{const data=await getJson(`${api}/api/v1/community/pick/${encodeURIComponent(slug)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({visitorId:p.id,displayName:name,active})});me={wallet:data.wallet,picks:data.picks};renderMe();await loadSpotlight();if(active)location.href=roomHref(slug)}catch(e){alert(e.code==='outside_radar'?'That act has crossed the NUGU RADAR mainstream gate.':e.code==='pick_limit'?'You can keep up to three active picks. Unpick one first.':e.status===401?'Your sign-in expired. Sign in again.':'Could not update My Radar.') }}
function searchCard(a){const picked=isPicked(a.slug),outside=a.radar_eligible===false;return `<article class="spotlight-card"><img src="${esc(a.image_url||'')}" alt="${esc(a.name)}" loading="lazy" referrerpolicy="no-referrer"><div><h3>${esc(a.name)}</h3><p>${esc(a.korean_name||'')} ${a.agency?`· ${esc(a.agency)}`:''}${outside?` · OUTSIDE RADAR`:(a.rank?` · #${esc(a.rank)}`:'')}</p></div><div class="community-card-actions">${outside?`<span class="verified-pill">${esc(a.radar_tier||'mainstream')}</span>`:picked?`<a href="${roomHref(a.slug)}">Room</a>`:`<button data-pick="${esc(a.slug)}">Pick</button>`}</div></article>`}
async function searchArtists(q){const root=$('#artistSearchResults');root.innerHTML='<div class="empty-community">Searching verified catalog…</div>';try{const data=await getJson(`${api}/api/v1/search?q=${encodeURIComponent(q)}`);root.innerHTML=data.items?.length?data.items.map(searchCard).join(''):`<div class="empty-community">No verified artist matched that search.</div>`;root.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>setPick(b.dataset.pick,true))}catch(e){root.innerHTML='<div class="empty-community">Search is unavailable right now.</div>'}}
function spotlightCard(a,i){return `<a class="spotlight-card" href="${roomHref(a.slug)}"><img src="${esc(a.image_url||'')}" alt="${esc(a.name)}" loading="lazy" referrerpolicy="no-referrer"><div><h3>${String(i+1).padStart(2,'0')} · ${esc(a.name)}</h3><p>${fmtTime(a.glow_24h_seconds)} lit in 24h · ${fmt(a.supporters)} supporters</p></div><div class="spotlight-score"><b>${fmt(Number(a.community_glow_score||0))}</b><span>GLOW SCORE</span></div></a>`}
async function loadSpotlight(){const root=$('#spotlightGrid');try{const data=await getJson(`${api}/api/v1/community/spotlight`);root.innerHTML=data.items?.length?data.items.map(spotlightCard).join(''):`<div class="empty-community">No Community Glow yet. The first eligible room to spend Radar Time takes the first spotlight.</div>`}catch(e){root.innerHTML='<div class="empty-community">Community Spotlight is warming up.</div>'}}
$('#artistSearch').onsubmit=e=>{e.preventDefault();const q=$('#artistSearchInput').value.trim();if(q)searchArtists(q)};
window.addEventListener('nugu-auth-changed',()=>loadMe());
$('#versionLabel').textContent=cfg.build||'Updated 2026.09.09';renderMe();loadMe();loadSpotlight();