const cfg=window.NUGU_CONFIG||{};const api=String(cfg.apiBase||'').replace(/\/$/,'');const params=new URLSearchParams(location.search);const slug=(params.get('artist')||'').trim().toLowerCase();
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtTime=s=>{const n=Math.max(0,Number(s||0));if(n<60)return`${Math.round(n)}s`;const m=Math.floor(n/60);if(m<60)return`${m}m`;const h=Math.floor(m/60),rm=m%60;return`${h}h ${rm}m`};
const fmtScene=s=>{const n=Math.max(0,Math.floor(Number(s)||0)),m=Math.floor(n/60),sec=n%60;return`${m}:${String(sec).padStart(2,'0')}`};
const parseScene=v=>{const p=String(v||'').trim().split(':').map(Number);if(p.some(x=>!Number.isFinite(x)))return 0;if(p.length===1)return Math.max(0,Math.floor(p[0]||0));if(p.length===2)return Math.max(0,Math.floor((p[0]||0)*60+(p[1]||0)));return Math.max(0,Math.floor((p[0]||0)*3600+(p[1]||0)*60+(p[2]||0)))};
const relative=d=>{if(!d)return'';const ms=Date.now()-Date.parse(d),m=Math.max(1,Math.floor(ms/60000));if(m<60)return`${m}분 전`;const h=Math.floor(m/60);if(h<24)return`${h}시간 전`;const days=Math.floor(h/24);return`${days}일 전`};
const dateLabel=d=>d?new Date(d).toLocaleDateString('ko-KR',{year:'numeric',month:'short',day:'numeric'}):'날짜 미상';
function visitor(){const a=window.NUGU_AUTH?.getIdentitySync?.();if(a)return{id:a.visitorId,name:a.displayName||localStorage.getItem('nuguCommentName')||'',authenticated:!!a.authenticated};let id=localStorage.getItem('nuguVisitorId');if(!id){id=(crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`).replace(/[^A-Za-z0-9_-]/g,'');localStorage.setItem('nuguVisitorId',id)}return{id,name:localStorage.getItem('nuguCommentName')||'',authenticated:false}}
function currentName(){const p=visitor();if(p.authenticated&&p.name)return p.name;return ($('#roomName')?.value||p.name||'').trim().slice(0,20)}
async function getJson(url,opts={}){let identity=null;try{identity=await window.NUGU_AUTH?.getIdentity?.()}catch(e){console.warn('auth session refresh failed',e)}const auth=window.NUGU_AUTH?.authHeaders?.(identity)||{};const r=await fetch(url,{...opts,headers:{Accept:'application/json',...auth,...(opts.headers||{})},cache:'no-store'});const data=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(data.error||`HTTP ${r.status}`),{code:data.error,data,status:r.status});return data}
let room=null,me={wallet:{earned:0,spent:0,balance:0},picks:[]},sessionEarned=0,lastActivity=Date.now(),heartbeatBusy=false,activeTab='talk',selectedVideoId=null,playerSeconds=0;
const picked=()=>me.picks?.some(x=>x.slug===slug);const insideRadar=()=>room?.artist?.radar_eligible!==false;
function setLocalName(name){if(!visitor().authenticated)(window.NUGU_AUTH?.setDisplayName?.(name)||localStorage.setItem('nuguCommentName',name))}
function ensureName(){let name=currentName();if(name.length<2)name=(prompt('아지트에서 쓸 닉네임을 정해줘')||'').trim().slice(0,20);if(name.length<2)return null;setLocalName(name);return name}

function postCard(p){return `<article class="room-post"><div class="room-post-head"><b>${esc(p.display_name||'NUGU fan')}</b><span>${relative(p.created_at)}</span></div><p>${esc(p.body||'')}</p></article>`}
function renderHero(){const a=room.artist,c=room.community||{},outside=!insideRadar();document.title=`${a.name} 아지트 — NUGU RADAR`;$('#roomHero').innerHTML=`<div class="hideout-hero-inner">
  <div class="hideout-polaroid">${a.image_url?`<img src="${esc(a.image_url)}" alt="${esc(a.name)}" referrerpolicy="no-referrer">`:'<div style="aspect-ratio:1;background:#eee9f2"></div>'}<span>our little ${esc(a.name)} room ♡</span></div>
  <div class="hideout-title"><span class="hideout-label">${outside?'ARCHIVED HIDEOUT':'FAN HIDEOUT · 우리방'}</span><h1>${esc(a.name)} <em>아지트</em></h1><p>${outside?'레이더 밖으로 졸업한 뒤에도 우리가 모은 영상과 처음 좋아했던 기록은 그대로 남아 있어요.':`${esc(a.korean_name||'')} 좋아하는 사람들끼리 떠들고, 같이 보고, 놓치기 싫은 순간을 모아두는 우리 방.`}</p><div class="hideout-doodle">좋아하는 마음이 작아지지 않는 곳  ♡  same fans, brighter tomorrow</div></div>
  <div class="hideout-stats">
    <div class="hideout-stat"><small>우리 사람들</small><b>${Number(c.supporters||0)}</b></div>
    <div class="hideout-stat"><small>수다 메모</small><b>${Number(c.room_posts||0)}</b></div>
    <div class="hideout-stat"><small>같이 보는 영상</small><b>${Number(c.room_video_pins||0)}</b></div>
    <div class="hideout-stat"><small>장면 수다</small><b>${Number(c.timestamp_notes||0)}</b></div>
  </div>
</div>`}
function renderPick(){const p=me.picks?.find(x=>x.slug===slug),outside=!insideRadar();$('#pickPanel').innerHTML=outside?`<h2>우리 기록은 그대로</h2><p>이 팀은 Radar 밖으로 졸업했지만 먼저 좋아했던 기록과 아지트는 남아 있어요.</p>${picked()?'<button class="pick-button secondary" id="pickToggle">My Radar에서 빼기</button>':''}<div class="community-message" id="pickMessage"></div>`:`<h2>${picked()?'내 레이더에 있어 ♡':'이 팀 찜하기'}</h2><p>${picked()?`처음 찍어둔 순간${p?.discovered_rank?` · 당시 #${esc(p.discovered_rank)}`:''}도 그대로 보관 중.`:'최대 세 팀까지 골라둘 수 있어요. Pick한 팀 아지트에서 Radar Time도 쌓여요.'}</p><button class="pick-button ${picked()?'secondary':''}" id="pickToggle">${picked()?'My Radar에서 빼기':'내 팀으로 Pick ♡'}</button><div class="community-message" id="pickMessage"></div>`;const b=$('#pickToggle');if(b)b.onclick=()=>setPick(outside?false:!picked())}
function renderTime(){const w=me.wallet||{},active=picked()&&insideRadar(),outside=!insideRadar();$('#timePanel').innerHTML=`<h2>Radar Time</h2><p>${outside?'졸업한 아지트에서는 시간이 더 쌓이지 않아요. 기록은 그대로 남습니다.':'이 방에서 진짜 머문 시간만 쌓여요. 숨긴 탭이나 가만히 둔 시간은 세지 않아요.'}</p><div class="timer-display" id="walletBalance">${fmtTime(w.balance)}</div><div class="timer-note">${fmtTime(w.earned)} 모음 · ${fmtTime(w.spent)} 보냄 · 이번 방문 ${fmtTime(sessionEarned)}</div><div class="glow-actions"><button class="glow-button" data-glow="60" ${!active||w.balance<60?'disabled':''}>응원 +1m</button><button class="glow-button" data-glow="300" ${!active||w.balance<300?'disabled':''}>응원 +5m</button></div><div class="community-message" id="glowMessage">${outside?'우리의 옛 기록 보관 중.':active?'모은 시간을 이 팀에게 보내기 ♡':'먼저 이 팀을 Pick해줘.'}</div>`;$('#timePanel').querySelectorAll('[data-glow]').forEach(b=>b.onclick=()=>spendGlow(Number(b.dataset.glow)))}
function renderFounders(){const founders=room.founders||[];$('#foundersPanel').innerHTML=`<h2>먼저 온 사람들</h2><p>언제부터 좋아했는지는 돈으로도, 나중에도 못 사요.</p><div class="founders">${founders.length?founders.map(f=>`<span class="founder-chip"><b>#${esc(f.founderIndex)}</b>${esc(f.display_name)}${f.earlyBadge?` <span class="early-badge">${esc(f.earlyBadge)}</span>`:''}</span>`).join(''):'<span class="timer-note">아직 아무도 첫 자리를 차지하지 않았어요.</span>'}</div>`}
function renderPosts(){$('#roomFeed').innerHTML=room.posts?.length?room.posts.map(postCard).join(''):'<div class="hideout-empty">첫 메모를 붙여줘. 나중에 이 방의 진짜 시작이 될지도 몰라 ♡</div>'}

function allVideos(){const m=new Map();for(const v of [...(room?.pinnedVideos||[]),...(room?.videoLibrary||[])])m.set(Number(v.content_id),{...(m.get(Number(v.content_id))||{}),...v});return [...m.values()]}
function selectedVideo(){const rows=allVideos();let v=rows.find(x=>Number(x.content_id)===Number(selectedVideoId));if(!v){v=(room?.pinnedVideos||[]).find(x=>x.playable)||(room?.videoLibrary||[]).find(x=>x.playable)||rows[0]||null;if(v)selectedVideoId=Number(v.content_id)}return v}
function videoThumb(v){return v?.thumbnail_url||room?.artist?.image_url||''}
function videoCard(v){const active=Number(v.content_id)===Number(selectedVideoId);return `<button class="hideout-video-card ${active?'active':''}" type="button" data-video-select="${Number(v.content_id)}"><span class="tape"></span>${videoThumb(v)?`<img src="${esc(videoThumb(v))}" alt="">`:''}<h4>${esc(v.title||'영상')}</h4><p>${v.source_available===false?'원본 비공개 · 기록 보관 중':`${Number(v.note_count||0)}개 장면 수다`}</p></button>`}
function noteCard(n,v){return `<article class="scene-note"><button type="button" data-seek="${Number(n.at_seconds||0)}">${fmtScene(n.at_seconds)}</button><div><b>${esc(n.display_name||'NUGU fan')}</b><p>${esc(n.body||'')}</p></div><small>${relative(n.created_at)}</small></article>`}
function renderWatch(){const root=$('#watchTogether');if(!root)return;const v=selectedVideo(),pins=room.pinnedVideos||[];if(!v){root.innerHTML='<div class="hideout-empty">아직 모아둔 영상이 없어. 보관함에서 첫 영상을 같이보기로 올려줘 ♡</div>';return}
  const notes=(room.timestampNotes||[]).filter(n=>Number(n.content_item_id)===Number(v.content_id)).sort((a,b)=>Number(a.at_seconds)-Number(b.at_seconds)||Date.parse(a.created_at)-Date.parse(b.created_at));
  const alreadyPinned=pins.some(x=>Number(x.content_id)===Number(v.content_id));
  const start=Math.max(0,Math.floor(playerSeconds||0));const origin=encodeURIComponent(location.origin);
  const topkkuHref=v.playback_id?`watch.html?artist=${encodeURIComponent(slug)}&video=${encodeURIComponent(v.playback_id)}&t=${start}&topkku=1`:'topkku.html';
  root.innerHTML=`<div class="hideout-player-card"><div class="hideout-player-wrap">${v.playable?`<iframe id="hideoutPlayer" src="https://www.youtube-nocookie.com/embed/${encodeURIComponent(v.playback_id)}?rel=0&playsinline=1&enablejsapi=1&origin=${origin}&start=${start}" title="${esc(v.title)}" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>`:`<div class="hideout-player-empty">원본 영상이 지금은 재생되지 않아요.<br>그래도 이 방에서 모았던 기록과 수다는 남아 있어요.</div>`}</div><div class="hideout-player-meta"><div><h3>${esc(v.title)}</h3><p>${esc(v.channel_name||room.artist.name)} · ${dateLabel(v.published_at)} ${v.archive_state==='ARCHIVED'?'· 아카이브':''}</p></div><div class="hideout-player-actions">${!alreadyPinned&&v.source_available!==false?`<button type="button" id="pinCurrentVideo">우리 같이보기에 넣기</button>`:'<button type="button" disabled>우리방에 보관됨 ♡</button>'}${v.playback_id?`<a id="sceneTopkkuLink" href="${topkkuHref}">✨ 이 장면 탑꾸</a>`:''}</div></div></div>
  ${insideRadar()&&v.source_available!==false?`<form class="scene-compose" id="sceneCompose"><input id="sceneTime" value="${fmtScene(playerSeconds)}" inputmode="numeric" aria-label="영상 시간"><textarea id="sceneText" maxlength="500" placeholder="0:43 표정 봐… 같은 장면 수다를 남겨줘"></textarea><button type="submit">이 초에 붙이기</button><div class="scene-state" id="sceneState">영상이 재생되는 동안 시간이 자동으로 따라가요 · 500자까지</div></form>`:''}
  <div class="scene-notes">${notes.length?notes.map(n=>noteCard(n,v)).join(''):'<div class="hideout-empty">아직 이 영상에 장면 수다가 없어. 첫 “여기 봐”를 남겨줘.</div>'}</div>
  <div class="pinned-shelf"><div class="pinned-shelf-head"><h3>우리 같이 보는 영상</h3><span>${pins.length}개 모음</span></div><div class="video-ribbon">${pins.length?pins.map(videoCard).join(''):'<div class="hideout-empty">보관함에서 영상을 올리면 여기에 차곡차곡 붙어요.</div>'}</div></div>`;
  wireWatch();
}
function renderLibrary(){const root=$('#hideoutLibrary'),pins=new Set((room.pinnedVideos||[]).map(x=>Number(x.content_id))),rows=room.videoLibrary||[];root.innerHTML=rows.length?rows.map(v=>`<article class="library-card">${videoThumb(v)?`<img src="${esc(videoThumb(v))}" alt="${esc(v.title)}" loading="lazy" referrerpolicy="no-referrer">`:''}<div class="library-copy"><h3>${esc(v.title)}</h3><p>${esc(v.channel_name||room.artist.name)} · ${dateLabel(v.published_at)}</p><div class="library-tags"><span>${esc(v.platform||'content')}</span><span>${v.archive_state==='ARCHIVED'?'오래된 보물':'최근 떡밥'}</span>${Number(v.note_count||0)?`<span>수다 ${Number(v.note_count)}</span>`:''}</div><div class="library-actions"><button type="button" data-library-video="${Number(v.content_id)}">${pins.has(Number(v.content_id))?'같이 보기':'같이보기에 넣기'}</button>${v.platform==='youtube'&&v.platform_content_id?`<a href="/watch/youtube/${encodeURIComponent(v.platform_content_id)}/">영구 기록</a>`:`<a href="${esc(v.content_url)}" target="_blank" rel="noopener">원본</a>`}</div></div></article>`).join(''):'<div class="hideout-empty">아직 모아온 콘텐츠가 없어요.</div>';
  root.querySelectorAll('[data-library-video]').forEach(b=>b.onclick=async()=>{const id=Number(b.dataset.libraryVideo),v=rows.find(x=>Number(x.content_id)===id);selectedVideoId=id;playerSeconds=0;if(!pins.has(id)&&insideRadar()&&v?.source_available!==false)await addPin(id);activeTab='watch';renderTabs();renderWatch()})
}
function renderTabs(){$$('[data-hideout-tab]').forEach(b=>b.classList.toggle('active',b.dataset.hideoutTab===activeTab));$$('[data-hideout-view]').forEach(v=>v.classList.toggle('active',v.dataset.hideoutView===activeTab))}
function renderAll(){renderHero();renderPick();renderTime();renderFounders();renderPosts();renderLibrary();renderWatch();renderTabs();const p=visitor();$('#roomName').value=p.name||'';$('#roomName').readOnly=!!p.authenticated||!insideRadar();$('#roomText').disabled=!insideRadar();$('#roomCompose button[type="submit"]').disabled=!insideRadar();$('#roomPostState').textContent=insideRadar()?'800자까지 · 우리끼리 남기는 메모':'졸업한 아지트 · 새 글은 잠시 멈춰 있어요';$('#roomName').title=p.authenticated?'로그인 계정의 이름을 사용해요':''}

function enablePlayerListening(){const frame=$('#hideoutPlayer');if(!frame?.contentWindow)return;const listen=()=>{try{frame.contentWindow.postMessage(JSON.stringify({event:'listening',id:'nugu-hideout'}),'*')}catch{}};frame.addEventListener('load',listen,{once:true});setTimeout(listen,50)}
function sendPlayer(func,args=[]){const frame=$('#hideoutPlayer');try{frame?.contentWindow?.postMessage(JSON.stringify({event:'command',func,args}),'*')}catch{}}
function seekPlayer(sec){playerSeconds=Math.max(0,Number(sec)||0);sendPlayer('seekTo',[playerSeconds,true]);sendPlayer('playVideo');const input=$('#sceneTime');if(input)input.value=fmtScene(playerSeconds);const link=$('#sceneTopkkuLink'),v=selectedVideo();if(link&&v?.playback_id)link.href=`watch.html?artist=${encodeURIComponent(slug)}&video=${encodeURIComponent(v.playback_id)}&t=${Math.floor(playerSeconds)}&topkku=1`}
function wireWatch(){enablePlayerListening();$('#pinCurrentVideo')?.addEventListener('click',()=>addPin(selectedVideoId));$$('[data-video-select]').forEach(b=>b.onclick=()=>{selectedVideoId=Number(b.dataset.videoSelect);playerSeconds=0;renderWatch()});$$('[data-seek]').forEach(b=>b.onclick=()=>seekPlayer(Number(b.dataset.seek)));const form=$('#sceneCompose');if(form)form.onsubmit=addSceneNote}

window.addEventListener('message',e=>{const frame=$('#hideoutPlayer');if(!frame||e.source!==frame.contentWindow)return;let data=e.data;try{if(typeof data==='string')data=JSON.parse(data)}catch{return}const t=Number(data?.info?.currentTime);if(Number.isFinite(t)&&t>=0){playerSeconds=t;const input=$('#sceneTime');if(input&&document.activeElement!==input)input.value=fmtScene(t);const link=$('#sceneTopkkuLink'),v=selectedVideo();if(link&&v?.playback_id)link.href=`watch.html?artist=${encodeURIComponent(slug)}&video=${encodeURIComponent(v.playback_id)}&t=${Math.floor(t)}&topkku=1`}});

async function loadMe(){if(!api)return;const p=visitor();me=await getJson(`${api}/api/v1/community/me?visitorId=${encodeURIComponent(p.id)}`)}
async function loadRoom(){if(!slug){location.href='community.html';return}room=await getJson(`${api}/api/v1/community/room/${encodeURIComponent(slug)}`);if(selectedVideoId&&!allVideos().some(v=>Number(v.content_id)===Number(selectedVideoId)))selectedVideoId=null}
async function refresh(){try{await Promise.all([loadMe(),loadRoom()]);renderAll()}catch(e){console.warn(e);$('#roomHero').innerHTML='<div class="hideout-loading">이 아지트를 불러오지 못했어요.</div>'}}
async function setPick(active){const name=ensureName();if(!name)return;const p=visitor(),msg=$('#pickMessage');if(msg)msg.textContent='바꾸는 중…';try{const data=await getJson(`${api}/api/v1/community/pick/${encodeURIComponent(slug)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({visitorId:p.id,displayName:name,active})});me={wallet:data.wallet,picks:data.picks};await loadRoom();renderAll()}catch(e){if(msg)msg.textContent=e.code==='outside_radar'?'이 팀은 Radar 밖으로 졸업했어요.':e.code==='pick_limit'?'세 팀까지 Pick할 수 있어요. Community에서 하나를 빼줘.':e.status===401?'로그인이 만료됐어요.':'My Radar를 바꾸지 못했어요.'}}
async function spendGlow(seconds){if(!insideRadar())return;const name=ensureName();if(!name)return;const p=visitor();$('#glowMessage').textContent='마음 보내는 중…';try{const data=await getJson(`${api}/api/v1/community/glow/${encodeURIComponent(slug)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({visitorId:p.id,displayName:name,seconds})});me.wallet=data.wallet;room.community=data.community;renderHero();renderTime();$('#glowMessage').textContent=`${room.artist.name}에게 ${fmtTime(seconds)} 보냈어 ♡`}catch(e){$('#glowMessage').textContent=e.code==='insufficient_radar_time'?'Radar Time이 조금 부족해. 방에서 더 놀다 와.':e.code==='pick_required'?'먼저 이 팀을 Pick해줘.':'지금은 보내지 못했어요.'}}
async function addPin(contentId){if(!insideRadar())return;const name=ensureName();if(!name)return;const p=visitor();try{const data=await getJson(`${api}/api/v1/community/room/${encodeURIComponent(slug)}/videos`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({visitorId:p.id,displayName:name,contentId})});room.pinnedVideos=data.hideout.pinnedVideos;room.videoLibrary=data.hideout.videoLibrary;room.timestampNotes=data.hideout.timestampNotes;room.community=data.community;selectedVideoId=Number(contentId);renderHero();renderLibrary();renderWatch()}catch(e){alert(e.code==='pin_rate_limit'?'조금 천천히 모아줘 ♡':e.code==='outside_radar'?'졸업한 아지트에는 새 영상을 추가할 수 없어요.':'영상을 같이보기에 넣지 못했어요.')}}
async function addSceneNote(e){e.preventDefault();if(!insideRadar())return;const v=selectedVideo(),name=ensureName(),state=$('#sceneState');if(!v||!name)return;const text=$('#sceneText').value.trim(),atSeconds=parseScene($('#sceneTime').value);if(!text){state.textContent='그 장면에서 하고 싶은 말을 적어줘.';return}state.textContent='메모 붙이는 중…';const p=visitor();try{await getJson(`${api}/api/v1/community/room/${encodeURIComponent(slug)}/video-notes`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({visitorId:p.id,displayName:name,contentId:v.content_id,atSeconds,text})});$('#sceneText').value='';playerSeconds=atSeconds;await loadRoom();renderHero();renderLibrary();renderWatch()}catch(err){const s=$('#sceneState');if(s)s.textContent=err.code==='note_rate_limit'?'조금만 천천히 얘기해줘 ♡':err.code==='duplicate_note'?'방금 같은 메모를 이미 붙였어.':'장면 메모를 붙이지 못했어요.'}}
function markActivity(){lastActivity=Date.now()}['pointerdown','keydown','touchstart','scroll'].forEach(ev=>addEventListener(ev,markActivity,{passive:true}));
async function heartbeat(){if(heartbeatBusy||!insideRadar()||!picked()||document.visibilityState!=='visible'||Date.now()-lastActivity>120000)return;const name=currentName();if(name.length<2)return;heartbeatBusy=true;try{const p=visitor(),eventKey=crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;const data=await getJson(`${api}/api/v1/community/time/${encodeURIComponent(slug)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({visitorId:p.id,displayName:name,seconds:60,eventKey})});if(data.awarded){sessionEarned+=Number(data.awarded);me.wallet=data.wallet;renderTime()}}catch(e){console.warn('radar heartbeat',e)}finally{heartbeatBusy=false}}
setInterval(heartbeat,60000);

$('#roomCompose').onsubmit=async e=>{e.preventDefault();if(!insideRadar())return;const name=ensureName(),text=$('#roomText').value.trim(),state=$('#roomPostState');if(!name)return;if(!text){state.textContent='한마디라도 적어줘 ♡';return}const p=visitor();state.textContent='메모 붙이는 중…';try{await getJson(`${api}/api/v1/community/room/${encodeURIComponent(slug)}/posts`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({visitorId:p.id,displayName:name,text})});$('#roomText').value='';state.textContent='붙였어 ♡';await loadRoom();renderHero();renderPosts()}catch(err){state.textContent=err.code==='post_rate_limit'?'너무 빨라! 잠깐만 쉬었다 써줘.':err.code==='duplicate_post'?'같은 메모가 이미 붙어 있어.':'지금은 메모를 붙이지 못했어요.'}};
$$('[data-hideout-tab]').forEach(b=>b.onclick=()=>{activeTab=b.dataset.hideoutTab;renderTabs();if(activeTab==='watch')setTimeout(enablePlayerListening,0)});
window.addEventListener('nugu-auth-changed',refresh);
$('#versionLabel').textContent=cfg.build||'Updated 2026.09.11';refresh();
