const cfg=window.NUGU_CONFIG||{};const api=String(cfg.apiBase||'').replace(/\/$/,'');const params=new URLSearchParams(location.search);const slug=(params.get('artist')||'').trim().toLowerCase();
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtTime=s=>{const n=Math.max(0,Number(s||0));if(n<60)return`${n}s`;const m=Math.floor(n/60);if(m<60)return`${m}m`;const h=Math.floor(m/60),rm=m%60;return`${h}h ${rm}m`};
const relative=d=>{if(!d)return'';const ms=Date.now()-Date.parse(d),m=Math.max(1,Math.floor(ms/60000));if(m<60)return`${m}m ago`;const h=Math.floor(m/60);if(h<24)return`${h}h ago`;const days=Math.floor(h/24);return`${days}d ago`};
function visitor(){let id=localStorage.getItem('nuguVisitorId');if(!id){id=(crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`).replace(/[^A-Za-z0-9_-]/g,'');localStorage.setItem('nuguVisitorId',id)}return{id,name:localStorage.getItem('nuguCommentName')||''}}
function currentName(){return ($('#roomName')?.value||localStorage.getItem('nuguCommentName')||'').trim().slice(0,20)}
async function getJson(url,opts){const r=await fetch(url,{headers:{Accept:'application/json',...(opts?.headers||{})},cache:'no-store',...opts});const data=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(data.error||`HTTP ${r.status}`),{code:data.error,data});return data}
let room=null,me={wallet:{earned:0,spent:0,balance:0},picks:[]},sessionEarned=0,lastActivity=Date.now(),heartbeatBusy=false;
const picked=()=>me.picks?.some(x=>x.slug===slug);
function postCard(p){return `<article class="room-post"><div class="room-post-head"><b>${esc(p.display_name||'NUGU user')}</b><span>${relative(p.created_at)}</span></div><p>${esc(p.body||'')}</p></article>`}
function renderHero(){const a=room.artist,c=room.community||{};document.title=`${a.name} Radar Room — NUGU RADAR`;$('#roomHero').innerHTML=`${a.image_url?`<img src="${esc(a.image_url)}" alt="${esc(a.name)}" referrerpolicy="no-referrer">`:'<div></div>'}<div class="room-title"><span class="kicker">RADAR ROOM · ${esc(a.activity_state||'verified').toUpperCase()}</span><h1>${esc(a.name)}</h1><p>${esc(a.korean_name||'')} ${a.rank?`· #${esc(a.rank)} Momentum`:''} · Community Glow never changes Momentum Rank</p></div><div class="room-stats"><div class="room-stat"><small>SUPPORTERS</small><b>${Number(c.supporters||0)}</b></div><div class="room-stat"><small>24H GLOW</small><b>${fmtTime(c.glow_24h_seconds)}</b></div><div class="room-stat"><small>ALL-TIME GLOW</small><b>${fmtTime(c.glow_total_seconds)}</b></div><div class="room-stat"><small>ROOM POSTS</small><b>${Number(c.room_posts||0)}</b></div></div>`}
function renderPick(){const p=me.picks?.find(x=>x.slug===slug);$('#pickPanel').innerHTML=`<h2>${picked()?'On My Radar':'Pick this act'}</h2><p>${picked()?`Your original pick stays stamped${p?.discovered_rank?` at #${esc(p.discovered_rank)}`:''}.`:'Pick up to three acts. You only earn Radar Time inside rooms you picked.'}</p><button class="pick-button ${picked()?'secondary':''}" id="pickToggle">${picked()?'Remove from My Radar':'Add to My Radar'}</button><div class="community-message" id="pickMessage"></div>`;$('#pickToggle').onclick=()=>setPick(!picked())}
function renderTime(){const w=me.wallet||{};const active=picked();$('#timePanel').innerHTML=`<h2>Radar Time</h2><p>Visible, active room time earns up to one minute per minute. Idle or hidden tabs stop earning.</p><div class="timer-display" id="walletBalance">${fmtTime(w.balance)}</div><div class="timer-note">${fmtTime(w.earned)} earned · ${fmtTime(w.spent)} spent · ${fmtTime(sessionEarned)} this visit</div><div class="glow-actions"><button class="glow-button" data-glow="60" ${!active||w.balance<60?'disabled':''}>Light +1m</button><button class="glow-button" data-glow="300" ${!active||w.balance<300?'disabled':''}>Light +5m</button></div><div class="community-message" id="glowMessage">${active?'Spend time deliberately.':'Pick this act first.'}</div>`;$('#timePanel').querySelectorAll('[data-glow]').forEach(b=>b.onclick=()=>spendGlow(Number(b.dataset.glow)))}
function renderFounders(){const founders=room.founders||[];$('#foundersPanel').innerHTML=`<h2>Founders wall</h2><p>Earliest supporters keep their original timestamp. You cannot buy or backdate this.</p><div class="founders">${founders.length?founders.map(f=>`<span class="founder-chip"><b>#${esc(f.founderIndex)}</b>${esc(f.display_name)}${f.earlyBadge?` <span class="early-badge">${esc(f.earlyBadge)}</span>`:''}</span>`).join(''):'<span class="timer-note">Nobody has claimed an early spot yet.</span>'}</div>`}
function renderPosts(){$('#roomFeed').innerHTML=room.posts?.length?room.posts.map(postCard).join(''):'<div class="empty-community">No room posts yet. Start the fandom archive.</div>'}
function renderAll(){renderHero();renderPick();renderTime();renderFounders();renderPosts();const p=visitor();$('#roomName').value=p.name||''}
async function loadMe(){if(!api)return;const p=visitor();me=await getJson(`${api}/api/v1/community/me?visitorId=${encodeURIComponent(p.id)}`)}
async function loadRoom(){if(!slug){location.href='community.html';return}room=await getJson(`${api}/api/v1/community/room/${encodeURIComponent(slug)}`)}
async function refresh(){try{await Promise.all([loadMe(),loadRoom()]);renderAll()}catch(e){console.warn(e);$('#roomHero').innerHTML='<div class="empty-community">This Radar Room could not be loaded.</div>'}}
async function setPick(active){let name=currentName();if(name.length<2){name=(prompt('Pick a nickname for NUGU RADAR')||'').trim().slice(0,20)}if(name.length<2)return;localStorage.setItem('nuguCommentName',name);const p=visitor();const msg=$('#pickMessage');if(msg)msg.textContent='Updating…';try{const data=await getJson(`${api}/api/v1/community/pick/${encodeURIComponent(slug)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({visitorId:p.id,displayName:name,active})});me={wallet:data.wallet,picks:data.picks};await loadRoom();renderAll()}catch(e){if(msg)msg.textContent=e.code==='pick_limit'?'Three active picks max. Remove one in Community first.':'Could not update My Radar.'}}
async function spendGlow(seconds){const name=currentName();if(name.length<2){$('#glowMessage').textContent='Set a nickname first.';return}localStorage.setItem('nuguCommentName',name);const p=visitor();$('#glowMessage').textContent='Lighting up…';try{const data=await getJson(`${api}/api/v1/community/glow/${encodeURIComponent(slug)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({visitorId:p.id,displayName:name,seconds})});me.wallet=data.wallet;room.community=data.community;renderHero();renderTime();$('#glowMessage').textContent=`You just gave ${fmtTime(seconds)} of your time to ${room.artist.name}.`}catch(e){$('#glowMessage').textContent=e.code==='insufficient_radar_time'?'Not enough Radar Time yet. Stay active in the room.':e.code==='pick_required'?'Pick this act first.':'Could not spend Radar Time.'}}
function markActivity(){lastActivity=Date.now()}['pointerdown','keydown','touchstart','scroll'].forEach(ev=>addEventListener(ev,markActivity,{passive:true}));
async function heartbeat(){if(heartbeatBusy||!picked()||document.visibilityState!=='visible'||Date.now()-lastActivity>120000)return;const name=currentName();if(name.length<2)return;heartbeatBusy=true;try{const p=visitor();const eventKey=crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;const data=await getJson(`${api}/api/v1/community/time/${encodeURIComponent(slug)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({visitorId:p.id,displayName:name,seconds:60,eventKey})});if(data.awarded){sessionEarned+=Number(data.awarded);me.wallet=data.wallet;renderTime()}}catch(e){console.warn('radar heartbeat',e)}finally{heartbeatBusy=false}}
setInterval(heartbeat,60000);
$('#roomCompose').onsubmit=async e=>{e.preventDefault();const name=currentName(),text=$('#roomText').value.trim(),state=$('#roomPostState');if(name.length<2){state.textContent='Nickname must be at least 2 characters.';return}if(!text){state.textContent='Write something first.';return}localStorage.setItem('nuguCommentName',name);const p=visitor();state.textContent='Posting…';try{await getJson(`${api}/api/v1/community/room/${encodeURIComponent(slug)}/posts`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({visitorId:p.id,displayName:name,text})});$('#roomText').value='';state.textContent='Posted.';await loadRoom();renderHero();renderFounders();renderPosts()}catch(err){state.textContent=err.code==='post_rate_limit'?'Too fast — wait a moment.':err.code==='duplicate_post'?'That was already posted.':'Could not post right now.'}}
$('#versionLabel').textContent=cfg.build||'Updated 2026.09.09';refresh();