const config=window.NUGU_CONFIG||{};const catalog=window.NUGU_PLATFORM_CATALOG||{};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=n=>Number.isFinite(Number(n))?new Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(Number(n)):'—';
const dateLabel=d=>!d?'Ongoing':new Intl.DateTimeFormat('en',{year:'numeric',month:'short',day:'numeric'}).format(new Date(d.length===10?`${d}T00:00:00Z`:d));
const platformLabel=id=>catalog[id]?.label||id;const platformBadge=id=>`<span class="platform-badge platform-${esc(id)}">${esc(platformLabel(id))}</span>`;
const params=new URLSearchParams(location.search);let artist=params.get('artist')||'';let platform='all',kind='all',sort='newest',offset=0,loading=false,hasMore=true,generation=0;
function card(c){return `<a class="watch-card" href="${esc(c.content_url)}" target="_blank" rel="noopener"><div class="watch-thumb">${c.thumbnail_url?`<img src="${esc(c.thumbnail_url)}" alt="${esc(c.title)} thumbnail" loading="lazy">`:`<div class="watch-placeholder">${esc(platformLabel(c.platform))}</div>`}<div class="watch-overlay"><span>${platformBadge(c.platform)}</span><b>↗</b></div></div><div class="watch-copy"><div class="watch-artist"><img src="${esc(c.artist_image_url||'')}" alt="" loading="lazy"><div><strong>${esc(c.artist_name)}</strong><small>${c.artist_rank?`#${esc(c.artist_rank)} momentum · `:''}${esc(c.kind||'Official content')}</small></div></div><h2>${esc(c.title)}</h2><p>${esc(c.channel_name||c.artist_name)} · ${dateLabel(c.published_at)}${c.public_metrics?.views!=null?` · ${fmt(c.public_metrics.views)} views`:''}</p><em>✓ ${esc(c.verification_rule||'Verified canonical source')}</em></div></a>`}
function setContext(){if(artist){$('#watchContext').innerHTML=`<span class="verified-pill">ARTIST FILTER</span><b>${esc(artist.replace(/-/g,' '))}</b><button id="clearArtist">Clear</button>`;$('#clearArtist').onclick=()=>{artist='';history.replaceState({},'',location.pathname);reset()}}else $('#watchContext').innerHTML='<span class="verified-pill">ALL VERIFIED ACTS</span><b>Infinite feed</b>'}
async function load(){if(loading||!hasMore)return;const myGen=generation;loading=true;$('#watchStatus').textContent=offset?'Loading more…':'Loading verified content…';try{const base=String(config.apiBase||'').replace(/\/$/,'');if(!base)throw new Error('API unavailable');const q=new URLSearchParams({limit:'24',offset:String(offset),platform,kind,sort});if(artist)q.set('artist',artist);const r=await fetch(`${base}/api/v1/content?${q}`,{headers:{Accept:'application/json'},cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const data=await r.json();if(myGen!==generation)return;const items=Array.isArray(data.items)?data.items:[];$('#watchFeed').insertAdjacentHTML('beforeend',items.map(card).join(''));offset=Number(data.nextOffset||offset+items.length);hasMore=Boolean(data.hasMore);$('#watchStatus').textContent=hasMore?`Loaded ${offset} · keep scrolling`:`End of verified results · ${offset} loaded`;}catch(e){if(myGen===generation)$('#watchStatus').textContent='Could not load verified content. Retry by changing a filter.';console.warn(e)}finally{if(myGen===generation)loading=false}}
function reset(){generation++;offset=0;hasMore=true;loading=false;$('#watchFeed').innerHTML='';setContext();load()}
function wireGroup(root,attr,setter){$$(root+' button').forEach(b=>b.onclick=()=>{$$(root+' button').forEach(x=>x.classList.remove('active'));b.classList.add('active');setter(b.dataset[attr]);reset()})}
wireGroup('#platformFilters','platform',v=>platform=v);wireGroup('#kindFilters','kind',v=>kind=v);wireGroup('#sortFilters','sort',v=>sort=v);
$('#versionLabel').textContent=config.build||'Updated 2026.09.05';setContext();
const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting))load()},{rootMargin:'700px 0px'});observer.observe($('#watchSentinel'));load();
