(()=>{
  const player=document.getElementById('watchPlayer');
  const playerBody=document.getElementById('playerBody');
  const feed=document.getElementById('watchFeed');
  let portraitNext=false,latestTime=0;
  const ytId=url=>{const s=String(url||'');let m=s.match(/(?:i\.ytimg\.com|img\.youtube\.com)\/vi\/([^/]+)\//i);if(m)return m[1];m=s.match(/[?&]v=([^&#]+)/i);if(m)return m[1];m=s.match(/youtu\.be\/([^?&#/]+)/i);return m?m[1]:''};
  function qualityCandidates(img){const original=img.dataset.direct||img.getAttribute('src')||'';const id=ytId(original)||ytId(img.getAttribute('src'));const rows=[];const push=u=>{if(u&&!rows.includes(u))rows.push(u)};if(id){push(`https://i.ytimg.com/vi/${encodeURIComponent(id)}/maxresdefault.jpg`);push(`https://i.ytimg.com/vi/${encodeURIComponent(id)}/sddefault.jpg`);push(`https://i.ytimg.com/vi/${encodeURIComponent(id)}/hqdefault.jpg`)}push(original);push(img.dataset.fallback);return rows}
  function upgradeThumb(img){if(!img||img.dataset.qualityWired)return;img.dataset.qualityWired='1';const candidates=qualityCandidates(img);if(!candidates.length)return;let idx=0;const apply=()=>{if(idx>=candidates.length){img.dataset.quality='fallback';return}img.src=candidates[idx];img.dataset.quality=idx===0?'max':idx===1?'sd':idx===2?'hq':'fallback'};img.addEventListener('error',()=>{idx++;apply()});img.addEventListener('load',()=>{if(img.naturalWidth&&img.naturalWidth<480&&idx<candidates.length-1){idx++;apply()}});apply()}
  function scanThumbs(root){if(!root)return;if(root.matches?.('.watch-thumb img'))upgradeThumb(root);root.querySelectorAll?.('.watch-thumb img').forEach(upgradeThumb)}
  function cardLooksPortrait(card){if(!card)return false;const kind=(card.querySelector('.watch-artist small')?.textContent||'').toLowerCase();const title=(card.querySelector('.watch-copy h2')?.textContent||'').toLowerCase();return kind.includes('shorts')||title.includes('#shorts')||title.includes(' shorts')}
  document.addEventListener('pointerdown',e=>{const card=e.target.closest?.('.watch-card');if(card)portraitNext=cardLooksPortrait(card)},true);
  document.addEventListener('keydown',e=>{if(e.key!=='Enter'&&e.key!==' ')return;const card=e.target.closest?.('.watch-card');if(card)portraitNext=cardLooksPortrait(card)},true);
  const playerIframe=()=>playerBody?.querySelector('.player-frame iframe')||null;
  function sendYoutube(func,args=[]){const frame=playerIframe();if(!frame?.contentWindow)return;try{frame.contentWindow.postMessage(JSON.stringify({event:'command',func,args}),'*')}catch{}}
  function enableYoutubeApi(){const frame=playerIframe();if(!frame||frame.dataset.nuguApiReady)return;frame.dataset.nuguApiReady='1';const listen=()=>{try{frame.contentWindow?.postMessage(JSON.stringify({event:'listening',id:'nugu-radar-watch'}),'*')}catch{}};frame.addEventListener('load',listen);setTimeout(listen,0)}
  const preciseTimeLabel=s=>{const n=Math.max(0,Number(s)||0),m=Math.floor(n/60),sec=n-m*60;return`${m}:${sec.toFixed(1).padStart(4,'0')}`};
  function updateSceneTime(){const el=playerBody?.querySelector('#frameTopkkuTime');if(el)el.textContent=preciseTimeLabel(latestTime)}
  window.addEventListener('message',e=>{const frame=playerIframe();if(!frame||e.source!==frame.contentWindow)return;let data=e.data;try{if(typeof data==='string')data=JSON.parse(data)}catch{return}const t=Number(data?.info?.currentTime);if(Number.isFinite(t)&&t>=0){latestTime=t;updateSceneTime()}});
  const wait=ms=>new Promise(r=>setTimeout(r,ms));
  async function nudgeFrame(delta){const buttons=playerBody?.querySelectorAll('.frame-nudge button')||[];buttons.forEach(b=>b.disabled=true);try{const next=Math.max(0,Math.round((Number(latestTime||0)+Number(delta||0))*10)/10);latestTime=next;sendYoutube('pauseVideo');sendYoutube('seekTo',[next,true]);updateSceneTime();await wait(120);sendYoutube('pauseVideo');captureMessage(`${preciseTimeLabel(next)} 장면을 골랐어요. 더 미세하게 맞추거나 바로 탑꾸해보세요.`,'picked')}finally{buttons.forEach(b=>b.disabled=false)}}
  async function videoFromStream(stream){const v=document.createElement('video');v.muted=true;v.playsInline=true;v.srcObject=stream;await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('capture_timeout')),6000);v.onloadedmetadata=()=>{clearTimeout(timer);resolve()};v.onerror=()=>{clearTimeout(timer);reject(new Error('capture_video_error'))}});await v.play();await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return v}
  function drawVideo(video,sx,sy,sw,sh){if(!sw||!sh)throw new Error('capture_scale');const maxSide=1200,scale=Math.min(1,maxSide/Math.max(sw,sh));const out=document.createElement('canvas');out.width=Math.max(1,Math.round(sw*scale));out.height=Math.max(1,Math.round(sh*scale));const c=out.getContext('2d');c.imageSmoothingEnabled=true;c.imageSmoothingQuality='high';c.drawImage(video,sx,sy,sw,sh,0,0,out.width,out.height);return out}
  function cropCurrentIframe(video){const frame=playerIframe();if(!frame)throw new Error('player_missing');const r=frame.getBoundingClientRect();if(r.width<80||r.height<80||r.bottom<=0||r.right<=0||r.top>=innerHeight||r.left>=innerWidth)throw new Error('player_not_visible');const vv=window.visualViewport;const vw=vv?.width||document.documentElement.clientWidth||innerWidth;const vh=vv?.height||document.documentElement.clientHeight||innerHeight;const ox=vv?.offsetLeft||0,oy=vv?.offsetTop||0;const scaleX=video.videoWidth/vw,scaleY=video.videoHeight/vh;if(!Number.isFinite(scaleX)||!Number.isFinite(scaleY)||scaleX<=0||scaleY<=0)throw new Error('capture_scale');const x=Math.max(0,(r.left-ox)*scaleX),y=Math.max(0,(r.top-oy)*scaleY),w=Math.min(video.videoWidth-x,r.width*scaleX),h=Math.min(video.videoHeight-y,r.height*scaleY);return drawVideo(video,x,y,w,h)}
  const canvasDataUrl=(canvas,quality=.9)=>new Promise((resolve,reject)=>{canvas.toBlob(blob=>{if(!blob)return reject(new Error('capture_encode'));const reader=new FileReader();reader.onload=()=>resolve(String(reader.result||''));reader.onerror=()=>reject(new Error('capture_encode'));reader.readAsDataURL(blob)},'image/jpeg',quality)});
  async function storeIncoming(canvas,meta){let image=await canvasDataUrl(canvas,.9);let payload={version:4,source:'watch',image,artist:meta.artist,title:meta.title,contentUrl:meta.contentUrl,time:meta.time,capturedAt:new Date().toISOString(),cleanCapture:true,finePicked:true};try{sessionStorage.setItem('nuguTopkkuIncoming',JSON.stringify(payload));return}catch{}const compact=document.createElement('canvas'),ratio=Math.min(1,900/Math.max(canvas.width,canvas.height));compact.width=Math.max(1,Math.round(canvas.width*ratio));compact.height=Math.max(1,Math.round(canvas.height*ratio));compact.getContext('2d').drawImage(canvas,0,0,compact.width,compact.height);payload.image=await canvasDataUrl(compact,.8);sessionStorage.setItem('nuguTopkkuIncoming',JSON.stringify(payload))}
  function captureMessage(text,state=''){const el=playerBody?.querySelector('#frameTopkkuState');if(el){el.textContent=text;el.dataset.state=state}}
  async function captureFrame(){const button=playerBody?.querySelector('#frameTopkkuButton');if(!button)return;if(!navigator.mediaDevices?.getDisplayMedia){captureMessage('이 브라우저는 바로 캡처를 지원하지 않아요. 스크린샷을 저장한 뒤 탑꾸 Lab에서 사진을 골라주세요.','error');return}const controls=playerBody?.querySelectorAll('.frame-topkku-action button')||[];controls.forEach(b=>b.disabled=true);const title=playerBody?.querySelector('.player-title h2')?.textContent?.trim()||'NUGU RADAR Watch';const metaLine=playerBody?.querySelector('.player-title p')?.textContent?.trim()||'';const artist=metaLine.split('·')[0]?.trim()||'';const sourceLink=playerBody?.querySelector('.player-title a')?.href||'';const clickedTime=Math.max(0,Number(latestTime)||0);let stream=null;try{captureMessage(`${preciseTimeLabel(clickedTime)} 장면을 준비 중이에요. 화면 공유에서 “현재 탭”을 선택해 주세요.`,'working');stream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false,preferCurrentTab:true,selfBrowserSurface:'include'});const track=stream.getVideoTracks()[0],surface=track?.getSettings?.().displaySurface;if(surface&&surface!=='browser')throw new Error('choose_current_tab');const video=await videoFromStream(stream);const targetTime=clickedTime,warmStart=Math.max(0,targetTime-.3);sendYoutube('seekTo',[warmStart,true]);sendYoutube('playVideo');await wait(650);let canvas=cropCurrentIframe(video);sendYoutube('pauseVideo');sendYoutube('seekTo',[targetTime,true]);latestTime=targetTime;updateSceneTime();await storeIncoming(canvas,{artist,title,contentUrl:sourceLink,time:targetTime});captureMessage(`${preciseTimeLabel(targetTime)} 장면을 가져왔어요. 탑꾸 Lab으로 이동합니다 ✨`,'success');setTimeout(()=>{location.href='topkku.html?from=watch'},220)}catch(err){console.warn('frame to topkku failed',err);sendYoutube('pauseVideo');sendYoutube('seekTo',[clickedTime,true]);latestTime=clickedTime;updateSceneTime();if(err?.name==='NotAllowedError')captureMessage('캡처를 취소했어요. 다시 누르면 언제든 할 수 있어요.','');else if(err?.message==='choose_current_tab')captureMessage('전체 화면이나 창 말고 “현재 탭”을 선택해 주세요. 그래야 영상만 정확히 가져올 수 있어요.','error');else if(err?.message==='player_not_visible')captureMessage('영상이 화면 안에 보이도록 한 뒤 다시 눌러주세요.','error');else captureMessage('장면을 가져오지 못했어요. 한 번 더 시도해 주세요.','error')}finally{stream?.getTracks?.().forEach(t=>t.stop());controls.forEach(b=>b.disabled=false)}}
  function wireFrameAction(){const title=playerBody?.querySelector('.player-title');if(!title||title.querySelector('#frameTopkkuButton'))return;enableYoutubeApi();const wrap=document.createElement('div');wrap.className='frame-topkku-action';wrap.innerHTML=`<div class="frame-scene-head"><b>딱 이 표정으로</b><strong id="frameTopkkuTime">${preciseTimeLabel(latestTime)}</strong></div><div class="frame-nudge" aria-label="장면 미세 선택"><button type="button" data-step="-0.2">−0.2초</button><button type="button" data-step="-0.1">−0.1초</button><button type="button" data-step="0.1">+0.1초</button><button type="button" data-step="0.2">+0.2초</button></div><button id="frameTopkkuButton" type="button">✨ 이 장면 탑꾸</button><span id="frameTopkkuState">원하는 표정에 맞춘 뒤 눌러보세요. 영상 밖 UI는 빼고 가져와요.</span>`;title.appendChild(wrap);wrap.querySelectorAll('.frame-nudge button').forEach(b=>b.addEventListener('click',()=>nudgeFrame(Number(b.dataset.step))));wrap.querySelector('#frameTopkkuButton').addEventListener('click',captureFrame);updateSceneTime()}
  function syncPlayer(){if(!player?.open)return;const title=(playerBody?.querySelector('.player-title h2')?.textContent||'').toLowerCase();const portrait=portraitNext||title.includes('#shorts')||title.includes(' shorts');player.classList.toggle('is-vertical',portrait);wireFrameAction();enableYoutubeApi();updateSceneTime()}
  window.addEventListener('nugu-watch-opened',syncPlayer);
  const playerObserver=new MutationObserver(()=>{if(player?.open)queueMicrotask(syncPlayer)});if(playerBody)playerObserver.observe(playerBody,{childList:true});
  const feedObserver=new MutationObserver(mutations=>{for(const m of mutations)for(const n of m.addedNodes)if(n.nodeType===1)scanThumbs(n)});if(feed)feedObserver.observe(feed,{childList:true});
  player?.addEventListener('close',()=>{player.classList.remove('is-vertical');portraitNext=false;latestTime=0});
  scanThumbs(feed);
})();
