const config=window.NUGU_CONFIG||{};const catalog=window.NUGU_PLATFORM_CATALOG||{};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=n=>Number.isFinite(Number(n))?new Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(Number(n)):'—';
const dateLabel=d=>!d?'Ongoing':new Intl.DateTimeFormat('en',{year:'numeric',month:'short',day:'numeric'}).format(new Date(d.length===10?`${d}T00:00:00Z`:d));
const relative=d=>{if(!d)return'';const ms=Date.now()-Date.parse(d);const m=Math.max(1,Math.floor(ms/60000));if(m<60)return`${m}m ago`;const h=Math.floor(m/60);if(h<24)return`${h}h ago`;const days=Math.floor(h/24);if(days<30)return`${days}d ago`;return dateLabel(d)};
const platformLabel=id=>catalog[id]?.label||id;const platformBadge=id=>`<span class="platform-badge platform-${esc(id)}">${esc(platformLabel(id))}</span>`;
const apiBase=()=>String(config.apiBase||'').replace(/\/$/,'');
const params=new URLSearchParams(location.search);let artist=params.get('artist')||'';let platform='all',kind='all',sort='newest',offset=0,cycle=0,loading=false,hasMore=true,generation=0;
const contentStore=new Map();
const keyOf=c=>`${c.platform}:${c.platform_content_id||c.content_id||c.content_url}`;
const continuousMode=()=>!artist&&platform==='all'&&kind==='all';
function thumbSrc(c){const base=apiBase();if(c.platform==='bstage'&&c.platform_content_id&&base)return `${base}/api/v1/content/${encodeURIComponent(c.platform)}/${encodeURIComponent(c.platform_content_id)}/thumbnail`;return c.thumbnail_url||''}
function card(c){const thumb=thumbSrc(c),key=keyOf(c),canPlay=c.playable&&c.playback_provider==='youtube';contentStore.set(key,c);return `<article class="watch-card" data-key="${esc(key)}" tabindex="0" role="button" aria-label="${canPlay?'Play':'Open'} ${esc(c.title)}"><div class="watch-thumb">${thumb?`<img src="${esc(thumb)}" data-direct="${esc(c.thumbnail_url||'')}" data-fallback="${esc(c.artist_image_url||'')}" alt="${esc(c.title)} thumbnail" loading="lazy" referrerpolicy="no-referrer">`:`<div class="watch-placeholder">${esc(platformLabel(c.platform))}</div>`}<div class="watch-overlay"><span>${platformBadge(c.platform)}</span><b>${canPlay?'▶':'↗'}</b></div></div><div class="watch-copy"><div class="watch-artist"><img src="${esc(c.artist_image_url||'')}" alt="" loading="lazy" referrerpolicy="no-referrer"><div><strong>${esc(c.artist_name)}</strong><small>${c.artist_rank?`#${esc(c.artist_rank)} momentum · `:''}${esc(c.kind||'Official content')}</small></div></div><h2>${esc(c.title)}</h2><p>${esc(c.channel_name||c.artist_name)} · ${dateLabel(c.published_at)}${c.public_metrics?.views!=null?` · ${fmt(c.public_metrics.views)} views`:''}</p><em>${canPlay?'▶ Play here · ':''}✓ ${esc(c.verification_rule||'Verified canonical source')}</em></div></article>`}
function wireThumbFallbacks(){$$('.watch-thumb img:not([data-thumb-wired])').forEach(img=>{img.dataset.thumbWired='1';let step=0;img.addEventListener('error',()=>{if(step===0&&img.dataset.direct&&img.src!==img.dataset.direct){step=1;img.src=img.dataset.direct;return}if(step<=1&&img.dataset.fallback){step=2;img.src=img.dataset.fallback;return}const box=img.closest('.watch-thumb');if(box){img.remove();if(!box.querySelector('.watch-placeholder'))box.insertAdjacentHTML('afterbegin','<div class="watch-placeholder">Thumbnail unavailable</div>')}})})}
function wireCards(){$$('.watch-card:not([data-card-wired])').forEach(el=>{el.dataset.cardWired='1';const open=()=>openContent(contentStore.get(el.dataset.key));el.onclick=open;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}}})}
function wireContextAction(){const start=$('#startFeed');if(start)start.onclick=async()=>{if(!offset)await load();$('#watchFeed').scrollIntoView({behavior:'smooth',block:'start'})}}
function setContext(){if(artist){$('#watchContext').innerHTML=`<span class="verified-pill">ARTIST FILTER</span><b>${esc(artist.replace(/-/g,' '))}</b><button id="clearArtist">Clear</button>`;$('#clearArtist').onclick=()=>{artist='';history.replaceState({},'',location.pathname);reset()}}else{$('#watchContext').innerHTML='<span class="verified-pill">ALL VERIFIED ACTS</span><button class="watch-jump" id="startFeed" type="button">Infinite feed ↓</button>';wireContextAction()}}
function nearSentinel(){const r=$('#watchSentinel').getBoundingClientRect();return r.top<innerHeight+800}
async function load(){if(loading||!hasMore)return;const myGen=generation;loading=true;$('#watchStatus').textContent=offset?`Loading more · cycle ${cycle+1}…`:'Loading verified content…';try{const base=apiBase();if(!base)throw new Error('API unavailable');const q=new URLSearchParams({limit:'24',offset:String(offset),cycle:String(cycle),platform,kind,sort});if(artist)q.set('artist',artist);const r=await fetch(`${base}/api/v1/content?${q}`,{headers:{Accept:'application/json'},cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const data=await r.json();if(myGen!==generation)return;const items=Array.isArray(data.items)?data.items:[];if(!items.length){hasMore=false;$('#watchStatus').textContent=offset?'All current filtered results loaded.':'No verified content for this filter.';return}$('#watchFeed').insertAdjacentHTML('beforeend',items.map(card).join(''));wireThumbFallbacks();wireCards();offset=Number(data.nextOffset||offset+items.length);hasMore=Boolean(data.hasMore);if(hasMore){$('#watchStatus').textContent=`Loaded ${offset} · keep scrolling`;}else if(continuousMode()){
      cycle+=1;offset=0;hasMore=true;$('#watchStatus').textContent=`All current items seen once · continuing with rotation ${cycle+1}`;
      if(nearSentinel())setTimeout(()=>load(),350);
    }else{$('#watchStatus').textContent=`All current filtered results loaded · ${offset} items`;}
  }catch(e){if(myGen===generation)$('#watchStatus').textContent='Could not load verified content. Retry by changing a filter.';console.warn(e)}finally{if(myGen===generation)loading=false}}
function reset(){generation++;offset=0;cycle=0;hasMore=true;loading=false;contentStore.clear();$('#watchFeed').innerHTML='';setContext();load()}
function wireGroup(root,attr,setter){$$(root+' button').forEach(b=>b.onclick=()=>{$$(root+' button').forEach(x=>x.classList.remove('active'));b.classList.add('active');setter(b.dataset[attr]);reset()})}
function visitorProfile(){let id=localStorage.getItem('nuguVisitorId');if(!id){id=(globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}-${Math.random()}`).replace(/[^A-Za-z0-9_-]/g,'');localStorage.setItem('nuguVisitorId',id)}return{id,name:localStorage.getItem('nuguCommentName')||''}}
function avatarLetter(name){return esc(String(name||'?').trim().slice(0,1).toUpperCase()||'?')}
function siteCommentBody(c){return `<div class="comment-row"><span class="comment-avatar">${avatarLetter(c.displayName)}</span><div><div class="comment-meta"><b>${esc(c.displayName||'NUGU user')}</b><span>${relative(c.createdAt)}</span></div><p>${esc(c.text||'')}</p></div></div>`}
function siteCommentMarkup(c){const replies=(c.replies||[]).map(r=>`<div class="comment-reply">${siteCommentBody(r)}</div>`).join('');return `<article class="site-comment">${siteCommentBody(c)}${replies}</article>`}
function commentErrorMessage(code){return({invalid_display_name:'Nickname must be 2–20 characters.',empty_comment:'Write something first.',comment_rate_limit:'Too fast — wait a moment before posting again.',daily_comment_limit:'Daily comment limit reached.',duplicate_comment:'That comment was already posted.'})[code]||'Comment could not be posted.'}
function commentsShell(data,profile){const rows=Array.isArray(data.items)?data.items:[];return `<div class="comments-head"><div><b>NUGU comments</b><span>Comments written by NUGU RADAR visitors · not imported from YouTube or other platforms</span></div><strong>${Number(data.total||rows.length)}</strong></div><form class="comment-compose" id="commentCompose"><div class="comment-profile"><input id="commentName" maxlength="20" autocomplete="nickname" placeholder="Nickname" value="${esc(profile.name)}"><span>Guest profile stays on this device</span></div><textarea id="commentText" maxlength="500" rows="3" placeholder="Say something about this video…"></textarea><div><small id="commentState">500 characters max</small><button type="submit" id="commentSubmit">Post comment</button></div></form><div id="commentList">${rows.length?rows.map(siteCommentMarkup).join(''):'<p class="comments-empty">No NUGU comments yet. Be the first.</p>'}</div>`}
function wireCommentComposer(c){const form=$('#commentCompose');if(!form)return;form.onsubmit=async e=>{e.preventDefault();const profile=visitorProfile(),name=$('#commentName').value.trim(),text=$('#commentText').value.trim(),button=$('#commentSubmit'),state=$('#commentState');if(name.length<2){state.textContent='Nickname must be at least 2 characters.';$('#commentName').focus();return}if(!text){state.textContent='Write a comment first.';$('#commentText').focus();return}localStorage.setItem('nuguCommentName',name);button.disabled=true;state.textContent='Posting…';try{const base=apiBase();const r=await fetch(`${base}/api/v1/content/${encodeURIComponent(c.platform)}/${encodeURIComponent(c.platform_content_id)}/comments`,{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({visitorId:profile.id,displayName:name,text})});const data=await r.json().catch(()=>({}));if(!r.ok){state.textContent=commentErrorMessage(data.error);return}$('#commentText').value='';await loadComments(c)}catch(err){state.textContent='Comment could not be posted right now.';console.warn(err)}finally{button.disabled=false}}}
async function loadComments(c){const root=$('#playerComments');if(!root)return;root.innerHTML='<div class="comments-loading">Loading NUGU comments…</div>';try{const base=apiBase();const r=await fetch(`${base}/api/v1/content/${encodeURIComponent(c.platform)}/${encodeURIComponent(c.platform_content_id)}/comments?limit=50`,{headers:{Accept:'application/json'},cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const data=await r.json();root.innerHTML=commentsShell(data,visitorProfile());wireCommentComposer(c)}catch(e){root.innerHTML='<p class="comments-empty">NUGU comments could not be loaded right now.</p>';console.warn(e)}}
function openContent(c){if(!c)return;if(!(c.playable&&c.playback_provider==='youtube'&&c.playback_id)){window.open(c.content_url,'_blank','noopener');return}const dlg=$('#watchPlayer');$('#playerBody').innerHTML=`<div class="player-frame"><iframe src="https://www.youtube-nocookie.com/embed/${encodeURIComponent(c.playback_id)}?autoplay=1&rel=0" title="${esc(c.title)}" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div><div class="player-info"><div class="player-title"><div>${platformBadge(c.platform)}<span class="verified-pill">✓ VERIFIED SOURCE</span></div><h2>${esc(c.title)}</h2><p>${esc(c.artist_name)} · ${esc(c.channel_name||c.artist_name)} · ${dateLabel(c.published_at)}</p><a href="${esc(c.content_url)}" target="_blank" rel="noopener">Open original source ↗</a></div><section class="player-comments" id="playerComments"></section></div>`;dlg.showModal();loadComments(c)}
function closePlayer(){const dlg=$('#watchPlayer');if(dlg.open)dlg.close();$('#playerBody').innerHTML=''}
wireGroup('#platformFilters','platform',v=>platform=v);wireGroup('#kindFilters','kind',v=>kind=v);wireGroup('#sortFilters','sort',v=>sort=v);
$('#playerClose').onclick=closePlayer;$('#watchPlayer').addEventListener('click',e=>{if(e.target===$('#watchPlayer'))closePlayer()});$('#watchPlayer').addEventListener('close',()=>{$('#playerBody').innerHTML=''});
$('#versionLabel').textContent=config.build||'Updated 2026.09.08';setContext();
const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting))load()},{rootMargin:'800px 0px'});observer.observe($('#watchSentinel'));load();
