(()=>{
  const player=document.getElementById('watchPlayer');
  const playerBody=document.getElementById('playerBody');
  const feed=document.getElementById('watchFeed');
  let portraitNext=false,latestTime=0;

  const ytId=url=>{const s=String(url||'');let m=s.match(/(?:i\.ytimg\.com|img\.youtube\.com)\/vi\/([^/]+)\//i);if(m)return m[1];m=s.match(/[?&]v=([^&#]+)/i);if(m)return m[1];m=s.match(/youtu\.be\/([^?&#/]+)/i);return m?m[1]:''};
  function qualityCandidates(img){const original=img.dataset.direct||img.getAttribute('src')||'';const id=ytId(original)||ytId(img.getAttribute('src'));const rows=[];const push=u=>{if(u&&!rows.includes(u))rows.push(u)};if(id){push(`https://i.ytimg.com/vi/${encodeURIComponent(id)}/maxresdefault.jpg`);push(`https://i.ytimg.com/vi/${encodeURIComponent(id)}/sddefault.jpg`);push(`https://i.ytimg.com/vi/${encodeURIComponent(id)}/hqdefault.jpg`)}push(original);push(img.dataset.fallback);return rows}
  function upgradeThumb(img){if(!img||img.dataset.qualityWired)return;img.dataset.qualityWired='1';const candidates=qualityCandidates(img);if(!candidates.length)return;let idx=0;const apply=()=>{if(idx>=candidates.length){img.dataset.quality='fallback';return}img.src=candidates[idx];img.dataset.quality=idx===0?'max':idx===1?'sd':idx===2?'hq':'fallback'};img.addEventListener('error',()=>{idx++;apply()});img.addEventListener('load',()=>{if(img.naturalWidth&&img.naturalWidth<480&&idx<candidates.length-1){idx++;apply()}});apply()}
  function scanThumbs(root){if(!root)return;if(root.matches?.('.watch-thumb img'))upgradeThumb(root);root.querySelectorAll?.('.watch-thumb img').forEach(upgradeThumb)}
  function cardLooksPortrait(card){if(!card)return false;const kind=(card.querySelector('.watch-artist small')?.textContent||'').toLowerCase();const title=(card.querySelector('.watch-copy h2')?.textContent||'').toLowerCase();return kind.includes('shorts')||title.includes('#shorts')||title.includes(' shorts')}
  document.addEventListener('pointerdown',e=>{const card=e.target.closest?.('.watch-card');if(card)portraitNext=cardLooksPortrait(card)},true);
  document.addEventListener('keydown',e=>{if(e.key!=='Enter'&&e.key!==' ')return;const card=e.target.closest?.('.watch-card');if(card)portraitNext=cardLooksPortrait(card)},true);

  const playerIframe=()=>playerBody?.querySelector('.player-frame iframe')||null;
  const playerFrame=()=>playerBody?.querySelector('.player-frame')||null;
  function sendYoutube(func,args=[]){const frame=playerIframe();if(!frame?.contentWindow)return;try{frame.contentWindow.postMessage(JSON.stringify({event:'command',func,args}),'*')}catch{}}
  function enableYoutubeApi(){const frame=playerIframe();if(!frame||frame.dataset.nuguApiReady)return;frame.dataset.nuguApiReady='1';const listen=()=>{try{frame.contentWindow?.postMessage(JSON.stringify({event:'listening',id:'nugu-radar-watch'}),'*')}catch{}};frame.addEventListener('load',listen);setTimeout(listen,0)}
  const preciseTimeLabel=s=>{const n=Math.max(0,Number(s)||0),m=Math.floor(n/60),sec=n-m*60;return`${m}:${sec.toFixed(1).padStart(4,'0')}`};
  function updateSceneTime(){const el=playerBody?.querySelector('#frameTopkkuTime');if(el)el.textContent=preciseTimeLabel(latestTime)}
  window.addEventListener('message',e=>{const frame=playerIframe();if(!frame||e.source!==frame.contentWindow)return;let data=e.data;try{if(typeof data==='string')data=JSON.parse(data)}catch{return}const t=Number(data?.info?.currentTime);if(Number.isFinite(t)&&t>=0){latestTime=t;updateSceneTime()}});
  const wait=ms=>new Promise(r=>setTimeout(r,ms));
  async function nudgeFrame(delta){const buttons=playerBody?.querySelectorAll('.frame-nudge button')||[];buttons.forEach(b=>b.disabled=true);try{const next=Math.max(0,Math.round((Number(latestTime||0)+Number(delta||0))*10)/10);latestTime=next;sendYoutube('pauseVideo');sendYoutube('seekTo',[next,true]);updateSceneTime();await wait(120);sendYoutube('pauseVideo');captureMessage(`${preciseTimeLabel(next)} 장면을 골랐어요. 더 미세하게 맞추거나 바로 탑꾸해보세요.`,'picked')}finally{buttons.forEach(b=>b.disabled=false)}}

  async function videoFromStream(stream){const v=document.createElement('video');v.muted=true;v.playsInline=true;v.srcObject=stream;await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('capture_timeout')),6000);v.onloadedmetadata=()=>{clearTimeout(timer);resolve()};v.onerror=()=>{clearTimeout(timer);reject(new Error('capture_video_error'))}});await v.play();await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return v}
  function frameCanvas(video){const c=document.createElement('canvas');c.width=video.videoWidth;c.height=video.videoHeight;c.getContext('2d').drawImage(video,0,0);return c}
  function drawCanvas(source,x,y,w,h,maxSide=1400){if(!w||!h)throw new Error('capture_scale');const scale=Math.min(1,maxSide/Math.max(w,h));const out=document.createElement('canvas');out.width=Math.max(1,Math.round(w*scale));out.height=Math.max(1,Math.round(h*scale));const c=out.getContext('2d');c.imageSmoothingEnabled=true;c.imageSmoothingQuality='high';c.drawImage(source,x,y,w,h,0,0,out.width,out.height);return out}

  const markerDefs=[{key:'tl',cls:'tl',rgb:[0,255,170]},{key:'tr',cls:'tr',rgb:[255,0,170]},{key:'bl',cls:'bl',rgb:[0,170,255]},{key:'br',cls:'br',rgb:[255,210,0]}];
  function addCalibrationMarkers(){const host=playerFrame();if(!host)return null;host.querySelector('.capture-calibration')?.remove();const layer=document.createElement('div');layer.className='capture-calibration';markerDefs.forEach(m=>{const s=document.createElement('i');s.className=m.cls;layer.appendChild(s)});host.appendChild(layer);return layer}
  function closeColor(r,g,b,target){const [tr,tg,tb]=target;return Math.abs(r-tr)<48&&Math.abs(g-tg)<48&&Math.abs(b-tb)<48&&Math.max(r,g,b)-Math.min(r,g,b)>120}
  function findMarker(data,w,h,target,ex,ey,range){const x0=Math.max(0,Math.floor(ex-range)),x1=Math.min(w-1,Math.ceil(ex+range)),y0=Math.max(0,Math.floor(ey-range)),y1=Math.min(h-1,Math.ceil(ey+range));let sx=0,sy=0,n=0;for(let y=y0;y<=y1;y+=2){for(let x=x0;x<=x1;x+=2){const i=(y*w+x)*4;if(closeColor(data[i],data[i+1],data[i+2],target)){sx+=x;sy+=y;n++}}}return n>=10?{x:sx/n,y:sy/n,n}:null}
  function calibratedRect(video,shot){const frame=playerIframe();if(!frame)return null;const r=frame.getBoundingClientRect(),vw=document.documentElement.clientWidth||innerWidth,vh=document.documentElement.clientHeight||innerHeight;const scaleX=video.videoWidth/vw,scaleY=video.videoHeight/vh;const expected={tl:[r.left*scaleX,r.top*scaleY],tr:[r.right*scaleX,r.top*scaleY],bl:[r.left*scaleX,r.bottom*scaleY],br:[r.right*scaleX,r.bottom*scaleY]};const data=shot.getContext('2d',{willReadFrequently:true}).getImageData(0,0,shot.width,shot.height).data;const range=Math.max(90,Math.min(240,Math.max(r.width*scaleX,r.height*scaleY)*.12));const hits={};for(const m of markerDefs){const [ex,ey]=expected[m.key];hits[m.key]=findMarker(data,shot.width,shot.height,m.rgb,ex,ey,range)}if(!hits.tl||!hits.tr||!hits.bl||!hits.br)return null;const left=(hits.tl.x+hits.bl.x)/2,right=(hits.tr.x+hits.br.x)/2,top=(hits.tl.y+hits.tr.y)/2,bottom=(hits.bl.y+hits.br.y)/2;if(right-left<120||bottom-top<120)return null;return{x:Math.max(0,left),y:Math.max(0,top),w:Math.min(shot.width-left,right-left),h:Math.min(shot.height-top,bottom-top),mode:'calibrated'}}
  function fallbackRect(video){const frame=playerIframe();if(!frame)throw new Error('player_missing');const r=frame.getBoundingClientRect();if(r.width<80||r.height<80||r.bottom<=0||r.right<=0||r.top>=innerHeight||r.left>=innerWidth)throw new Error('player_not_visible');const vw=document.documentElement.clientWidth||innerWidth,vh=document.documentElement.clientHeight||innerHeight;const scaleX=video.videoWidth/vw,scaleY=video.videoHeight/vh;const x=Math.max(0,r.left*scaleX),y=Math.max(0,r.top*scaleY),w=Math.min(video.videoWidth-x,r.width*scaleX),h=Math.min(video.videoHeight-y,r.height*scaleY);return{x,y,w,h,mode:'geometry'}}

  function darkRatioColumn(data,w,h,x,y0,y1){let dark=0,n=0;const step=Math.max(1,Math.floor((y1-y0)/140));for(let y=y0;y<y1;y+=step){const i=(y*w+x)*4,l=(data[i]+data[i+1]+data[i+2])/3;n++;if(l<24)dark++}return n?dark/n:0}
  function darkRatioRow(data,w,h,y,x0,x1){let dark=0,n=0;const step=Math.max(1,Math.floor((x1-x0)/140));for(let x=x0;x<x1;x+=step){const i=(y*w+x)*4,l=(data[i]+data[i+1]+data[i+2])/3;n++;if(l<24)dark++}return n?dark/n:0}
  function trimLetterbox(canvas,portrait){const w=canvas.width,h=canvas.height;if(w<180||h<180)return canvas;const ctx=canvas.getContext('2d',{willReadFrequently:true}),data=ctx.getImageData(0,0,w,h).data;const y0=Math.floor(h*.16),y1=Math.ceil(h*.84);let left=0,right=w-1,run=0;for(let x=0;x<Math.floor(w*.42);x+=2){if(darkRatioColumn(data,w,h,x,y0,y1)>.88)run++;else run=0;if(run<3)left=x+2;else if(x>12)left=x-4}run=0;for(let x=w-1;x>Math.ceil(w*.58);x-=2){if(darkRatioColumn(data,w,h,x,y0,y1)>.88)run++;else run=0;if(run<3)right=x-2;else if(w-1-x>12)right=x+4}left=Math.max(0,Math.min(left,Math.floor(w*.38)));right=Math.min(w-1,Math.max(right,Math.ceil(w*.62)));const x0=Math.max(left,Math.floor(w*.15)),x1=Math.min(right,Math.ceil(w*.85));let top=0,bottom=h-1;run=0;for(let y=0;y<Math.floor(h*.18);y+=2){if(darkRatioRow(data,w,h,y,x0,x1)>.9)run++;else run=0;if(run<3)top=y+2;else if(y>10)top=y-4}run=0;for(let y=h-1;y>Math.ceil(h*.82);y-=2){if(darkRatioRow(data,w,h,y,x0,x1)>.9)run++;else run=0;if(run<3)bottom=y-2;else if(h-1-y>10)bottom=y+4}let cw=right-left+1,ch=bottom-top+1;if(cw<w*.45||ch<h*.58){left=0;right=w-1;top=0;bottom=h-1;cw=w;ch=h}if(portrait&&cw/ch>.72){const target=Math.min(cw,ch*9/16),cx=(left+right)/2;left=Math.max(left,cx-target/2);right=Math.min(right,cx+target/2);cw=right-left+1}return drawCanvas(canvas,left,top,cw,bottom-top+1,1600)}
  function rowEdgeScore(data,w,h,y,x0,x1){let edges=0,n=0;for(let x=x0+2;x<x1-2;x+=2){const i=(y*w+x)*4,j=(y*w+x-2)*4;const l=(data[i]+data[i+1]+data[i+2])/3,p=(data[j]+data[j+1]+data[j+2])/3;n++;if(Math.abs(l-p)>72&&Math.max(data[i],data[i+1],data[i+2])>150)edges++}return n?edges/n:0}
  function trimCutEdgeText(canvas){const w=canvas.width,h=canvas.height;if(w<220||h<260)return canvas;const ctx=canvas.getContext('2d',{willReadFrequently:true}),data=ctx.getImageData(0,0,w,h).data;const x0=Math.floor(w*.05),x1=Math.floor(w*.76),start=Math.floor(h*.9);let noisy=0,first=h;for(let y=start;y<h;y+=2){const score=rowEdgeScore(data,w,h,y,x0,x1);if(score>.055){noisy++;first=Math.min(first,y)}}if(noisy<3||first>h*.965)return canvas;const trim=Math.min(h*.08,Math.max(0,h-first+4));if(trim<5)return canvas;return drawCanvas(canvas,0,0,w,h-trim,1600)}

  const canvasDataUrl=(canvas,quality=.91)=>new Promise((resolve,reject)=>{canvas.toBlob(blob=>{if(!blob)return reject(new Error('capture_encode'));const reader=new FileReader();reader.onload=()=>resolve(String(reader.result||''));reader.onerror=()=>reject(new Error('capture_encode'));reader.readAsDataURL(blob)},'image/jpeg',quality)});
  async function storeIncoming(canvas,meta){let image=await canvasDataUrl(canvas,.91);let payload={version:5,source:'watch',image,artist:meta.artist,title:meta.title,contentUrl:meta.contentUrl,time:meta.time,capturedAt:new Date().toISOString(),cleanCapture:true,finePicked:true,videoOnly:true,captureMode:meta.captureMode||'auto'};try{sessionStorage.setItem('nuguTopkkuIncoming',JSON.stringify(payload));return}catch{}const compact=document.createElement('canvas'),ratio=Math.min(1,960/Math.max(canvas.width,canvas.height));compact.width=Math.max(1,Math.round(canvas.width*ratio));compact.height=Math.max(1,Math.round(canvas.height*ratio));compact.getContext('2d').drawImage(canvas,0,0,compact.width,compact.height);payload.image=await canvasDataUrl(compact,.82);sessionStorage.setItem('nuguTopkkuIncoming',JSON.stringify(payload))}
  function captureMessage(text,state=''){const el=playerBody?.querySelector('#frameTopkkuState');if(el){el.textContent=text;el.dataset.state=state}}

  async function captureFrame(){const button=playerBody?.querySelector('#frameTopkkuButton');if(!button)return;if(!navigator.mediaDevices?.getDisplayMedia){captureMessage('이 브라우저는 바로 캡처를 지원하지 않아요. 스크린샷을 저장한 뒤 탑꾸 Lab에서 사진을 골라주세요.','error');return}const controls=playerBody?.querySelectorAll('.frame-topkku-action button')||[];controls.forEach(b=>b.disabled=true);const title=playerBody?.querySelector('.player-title h2')?.textContent?.trim()||'NUGU RADAR Watch';const metaLine=playerBody?.querySelector('.player-title p')?.textContent?.trim()||'';const artist=metaLine.split('·')[0]?.trim()||'';const sourceLink=playerBody?.querySelector('.player-title a')?.href||'';const clickedTime=Math.max(0,Number(latestTime)||0);let stream=null,markers=null;try{captureMessage(`${preciseTimeLabel(clickedTime)} 장면에서 실제 영상 영역만 찾고 있어요. “현재 탭”을 선택해 주세요.`,'working');stream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false,preferCurrentTab:true,selfBrowserSurface:'include'});const track=stream.getVideoTracks()[0],surface=track?.getSettings?.().displaySurface;if(surface&&surface!=='browser')throw new Error('choose_current_tab');const video=await videoFromStream(stream);markers=addCalibrationMarkers();await wait(220);const calibrationShot=frameCanvas(video);const calibrated=calibratedRect(video,calibrationShot);markers?.remove();markers=null;await wait(180);const targetTime=clickedTime,warmStart=Math.max(0,targetTime-.35);sendYoutube('seekTo',[warmStart,true]);sendYoutube('playVideo');await wait(850);const liveShot=frameCanvas(video),rect=calibrated||fallbackRect(video);let canvas=drawCanvas(liveShot,rect.x,rect.y,rect.w,rect.h,1600);sendYoutube('pauseVideo');sendYoutube('seekTo',[targetTime,true]);latestTime=targetTime;updateSceneTime();canvas=trimLetterbox(canvas,player?.classList.contains('is-vertical'));canvas=trimCutEdgeText(canvas);await storeIncoming(canvas,{artist,title,contentUrl:sourceLink,time:targetTime,captureMode:rect.mode});captureMessage(`${preciseTimeLabel(targetTime)} 장면에서 영상만 깔끔하게 가져왔어요 ✨`,'success');setTimeout(()=>{location.href='topkku.html?from=watch'},220)}catch(err){console.warn('frame to topkku failed',err);sendYoutube('pauseVideo');sendYoutube('seekTo',[clickedTime,true]);latestTime=clickedTime;updateSceneTime();if(err?.name==='NotAllowedError')captureMessage('캡처를 취소했어요. 다시 누르면 언제든 할 수 있어요.','');else if(err?.message==='choose_current_tab')captureMessage('전체 화면이나 창 말고 “현재 탭”을 선택해 주세요. 그래야 영상만 정확히 가져올 수 있어요.','error');else if(err?.message==='player_not_visible')captureMessage('영상이 화면 안에 보이도록 한 뒤 다시 눌러주세요.','error');else captureMessage('장면을 가져오지 못했어요. 한 번 더 시도해 주세요.','error')}finally{markers?.remove();stream?.getTracks?.().forEach(t=>t.stop());controls.forEach(b=>b.disabled=false)}}

  function wireFrameAction(){const title=playerBody?.querySelector('.player-title');if(!title||title.querySelector('#frameTopkkuButton'))return;enableYoutubeApi();const wrap=document.createElement('div');wrap.className='frame-topkku-action';wrap.innerHTML=`<div class="frame-scene-head"><b>딱 이 표정으로</b><strong id="frameTopkkuTime">${preciseTimeLabel(latestTime)}</strong></div><div class="frame-nudge" aria-label="장면 미세 선택"><button type="button" data-step="-0.2">−0.2초</button><button type="button" data-step="-0.1">−0.1초</button><button type="button" data-step="0.1">+0.1초</button><button type="button" data-step="0.2">+0.2초</button></div><button id="frameTopkkuButton" type="button">✨ 이 장면 탑꾸</button><span id="frameTopkkuState">원하는 표정에 맞춘 뒤 눌러보세요. 실제 영상 영역만 찾아서 가져와요.</span>`;title.appendChild(wrap);wrap.querySelectorAll('.frame-nudge button').forEach(b=>b.addEventListener('click',()=>nudgeFrame(Number(b.dataset.step))));wrap.querySelector('#frameTopkkuButton').addEventListener('click',captureFrame);updateSceneTime()}
  function lockPage(){document.documentElement.classList.add('nugu-watch-modal-open');document.body.classList.add('nugu-watch-modal-open')}
  function unlockPage(){document.documentElement.classList.remove('nugu-watch-modal-open');document.body.classList.remove('nugu-watch-modal-open')}
  function syncPlayer(){if(!player?.open)return;const title=(playerBody?.querySelector('.player-title h2')?.textContent||'').toLowerCase();const portrait=portraitNext||title.includes('#shorts')||title.includes(' shorts');player.classList.toggle('is-vertical',portrait);lockPage();wireFrameAction();enableYoutubeApi();updateSceneTime()}
  window.addEventListener('nugu-watch-opened',syncPlayer);
  const playerObserver=new MutationObserver(()=>{if(player?.open)queueMicrotask(syncPlayer)});if(playerBody)playerObserver.observe(playerBody,{childList:true});
  const feedObserver=new MutationObserver(mutations=>{for(const m of mutations)for(const n of m.addedNodes)if(n.nodeType===1)scanThumbs(n)});if(feed)feedObserver.observe(feed,{childList:true});
  player?.addEventListener('close',()=>{unlockPage();player.classList.remove('is-vertical');portraitNext=false;latestTime=0});
  scanThumbs(feed);
})();
