(()=>{
  const player=document.getElementById('watchPlayer');
  const playerBody=document.getElementById('playerBody');
  let portraitNext=false,latestTime=0,currentFrame=null;
  const ytId=url=>{const s=String(url||'');let m=s.match(/(?:i\.ytimg\.com|img\.youtube\.com)\/vi\/([^/]+)\//i);if(m)return m[1];m=s.match(/[?&]v=([^&#]+)/i);if(m)return m[1];m=s.match(/youtu\.be\/([^?&#/]+)/i);return m?m[1]:''};
  function qualityCandidates(img){const original=img.dataset.direct||img.getAttribute('src')||'';const id=ytId(original)||ytId(img.getAttribute('src'));const rows=[];const push=u=>{if(u&&!rows.includes(u))rows.push(u)};if(id){push(`https://i.ytimg.com/vi/${encodeURIComponent(id)}/maxresdefault.jpg`);push(`https://i.ytimg.com/vi/${encodeURIComponent(id)}/sddefault.jpg`);push(`https://i.ytimg.com/vi/${encodeURIComponent(id)}/hqdefault.jpg`)}push(original);push(img.dataset.fallback);return rows}
  function upgradeThumb(img){if(!img||img.dataset.qualityWired)return;img.dataset.qualityWired='1';const candidates=qualityCandidates(img);if(!candidates.length)return;let idx=0;const apply=()=>{if(idx>=candidates.length){img.dataset.quality='fallback';return}img.src=candidates[idx];img.dataset.quality=idx===0?'max':idx===1?'sd':idx===2?'hq':'fallback'};img.addEventListener('error',()=>{idx++;apply()});img.addEventListener('load',()=>{if(img.naturalWidth&&img.naturalWidth<480&&idx<candidates.length-1){idx++;apply()}});apply()}
  function scanThumbs(root=document){root.querySelectorAll?.('.watch-thumb img').forEach(upgradeThumb)}
  function cardLooksPortrait(card){if(!card)return false;const kind=(card.querySelector('.watch-artist small')?.textContent||'').toLowerCase();const title=(card.querySelector('.watch-copy h2')?.textContent||'').toLowerCase();return kind.includes('shorts')||title.includes('#shorts')||title.includes(' shorts')}
  document.addEventListener('pointerdown',e=>{const card=e.target.closest?.('.watch-card');if(card)portraitNext=cardLooksPortrait(card)},true);
  document.addEventListener('keydown',e=>{if(e.key!=='Enter'&&e.key!==' ')return;const card=e.target.closest?.('.watch-card');if(card)portraitNext=cardLooksPortrait(card)},true);
  const playerIframe=()=>playerBody?.querySelector('.player-frame iframe')||null;
  function sendYoutube(func,args=[]){const frame=playerIframe();if(!frame?.contentWindow)return;frame.contentWindow.postMessage(JSON.stringify({event:'command',func,args}),'*')}
  function enableYoutubeApi(){const frame=playerIframe();if(!frame||frame.dataset.nuguApiReady)return;frame.dataset.nuguApiReady='1';try{const u=new URL(frame.src);u.searchParams.set('enablejsapi','1');u.searchParams.set('origin',location.origin);frame.src=u.toString()}catch{}frame.addEventListener('load',()=>{try{frame.contentWindow.postMessage(JSON.stringify({event:'listening',id:'nugu-radar-watch'}),'*')}catch{}},{once:false})}
  window.addEventListener('message',e=>{const frame=playerIframe();if(!frame||e.source!==frame.contentWindow)return;let data=e.data;try{if(typeof data==='string')data=JSON.parse(data)}catch{return}const t=Number(data?.info?.currentTime);if(Number.isFinite(t)&&t>=0)latestTime=t});
  const timeLabel=s=>{const n=Math.max(0,Math.floor(Number(s)||0)),m=Math.floor(n/60),sec=n%60;return`${m}:${String(sec).padStart(2,'0')}`};
  async function videoFromStream(stream){const v=document.createElement('video');v.muted=true;v.playsInline=true;v.srcObject=stream;await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('capture_timeout')),8000);v.onloadedmetadata=()=>{clearTimeout(timer);resolve()};v.onerror=()=>{clearTimeout(timer);reject(new Error('capture_video_error'))}});await v.play();await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return v}
  function cropCurrentIframe(video){const frame=playerIframe();if(!frame)throw new Error('player_missing');const r=frame.getBoundingClientRect();if(r.width<80||r.height<80||r.bottom<=0||r.right<=0||r.top>=innerHeight||r.left>=innerWidth)throw new Error('player_not_visible');const sx=video.videoWidth/innerWidth,sy=video.videoHeight/innerHeight;if(!Number.isFinite(sx)||!Number.isFinite(sy)||sx<=0||sy<=0)throw new Error('capture_scale');const source={x:Math.max(0,r.left*sx),y:Math.max(0,r.top*sy),w:Math.min(video.videoWidth,r.width*sx),h:Math.min(video.videoHeight,r.height*sy)};const maxSide=1600,scale=Math.min(1,maxSide/Math.max(source.w,source.h));const out=document.createElement('canvas');out.width=Math.max(1,Math.round(source.w*scale));out.height=Math.max(1,Math.round(source.h*scale));const c=out.getContext('2d');c.imageSmoothingEnabled=true;c.imageSmoothingQuality='high';c.drawImage(video,source.x,source.y,source.w,source.h,0,0,out.width,out.height);return out}
  function encodeCanvas(canvas,quality=.92){return canvas.toDataURL('image/jpeg',quality)}
  function storeIncoming(canvas,meta){let image=encodeCanvas(canvas,.92);let payload={version:1,source:'watch',image,artist:meta.artist,title:meta.title,contentUrl:meta.contentUrl,time:meta.time,capturedAt:new Date().toISOString()};try{sessionStorage.setItem('nuguTopkkuIncoming',JSON.stringify(payload));return}catch{}const compact=document.createElement('canvas'),ratio=Math.min(1,1280/Math.max(canvas.width,canvas.height));compact.width=Math.max(1,Math.round(canvas.width*ratio));compact.height=Math.max(1,Math.round(canvas.height*ratio));compact.getContext('2d').drawImage(canvas,0,0,compact.width,compact.height);payload.image=encodeCanvas(compact,.82);sessionStorage.setItem('nuguTopkkuIncoming',JSON.stringify(payload))}
  function captureMessage(text,state=''){const el=playerBody?.querySelector('#frameTopkkuState');if(el){el.textContent=text;el.dataset.state=state}}
  async function captureFrame(){const button=playerBody?.querySelector('#frameTopkkuButton');if(!button)return;if(!navigator.mediaDevices?.getDisplayMedia){captureMessage('이 브라우저는 바로 캡처를 지원하지 않아요. 스크린샷을 저장한 뒤 탑꾸 Lab에서 사진을 골라주세요.','error');return}button.disabled=true;const frame=playerIframe();const title=playerBody?.querySelector('.player-title h2')?.textContent?.trim()||'NUGU RADAR Watch';const metaLine=playerBody?.querySelector('.player-title p')?.textContent?.trim()||'';const artist=metaLine.split('·')[0]?.trim()||'';const sourceLink=playerBody?.querySelector('.player-title a')?.href||'';const clickedTime=latestTime;try{sendYoutube('pauseVideo');captureMessage('화면 공유에서 꼭 “현재 탭”을 선택해 주세요. 영상 부분만 잘라서 가져올게요.','working');const stream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false,preferCurrentTab:true});try{const track=stream.getVideoTracks()[0],surface=track?.getSettings?.().displaySurface;if(surface&&surface!=='browser')throw new Error('choose_current_tab');const video=await videoFromStream(stream);const ratioCapture=video.videoWidth/video.videoHeight,ratioViewport=innerWidth/innerHeight;if(!surface&&Math.abs(ratioCapture-ratioViewport)/ratioViewport>.28)throw new Error('choose_current_tab');const canvas=cropCurrentIframe(video);currentFrame=canvas;storeIncoming(canvas,{artist,title,contentUrl:sourceLink,time:Number.isFinite(clickedTime)?clickedTime:latestTime});captureMessage('장면을 가져왔어요. 탑꾸 Lab으로 이동합니다 ✨','success');setTimeout(()=>{location.href='topkku.html?from=watch'},260)}finally{stream.getTracks().forEach(t=>t.stop())}}catch(err){console.warn('frame to topkku failed',err);if(err?.name==='NotAllowedError')captureMessage('캡처를 취소했어요. 다시 누르면 언제든 할 수 있어요.','');else if(err?.message==='choose_current_tab')captureMessage('전체 화면이나 창 말고, “현재 탭”을 선택해 주세요. 그래야 영상 장면만 정확히 잘라낼 수 있어요.','error');else if(err?.message==='player_not_visible')captureMessage('영상이 화면 안에 보이도록 한 뒤 다시 눌러주세요.','error');else captureMessage('장면을 가져오지 못했어요. 한 번 더 시도해 주세요.','error')}finally{button.disabled=false}}
  function wireFrameAction(){const title=playerBody?.querySelector('.player-title');if(!title||title.querySelector('#frameTopkkuButton'))return;enableYoutubeApi();const wrap=document.createElement('div');wrap.className='frame-topkku-action';wrap.innerHTML=`<button id="frameTopkkuButton" type="button">✨ 이 장면 탑꾸</button><span id="frameTopkkuState">마음에 드는 장면에서 눌러보세요. 사진은 서버에 올라가지 않아요.</span>`;title.appendChild(wrap);wrap.querySelector('button').addEventListener('click',captureFrame)}
  function syncPlayer(){if(!player)return;const title=(playerBody?.querySelector('.player-title h2')?.textContent||'').toLowerCase();const portrait=portraitNext||title.includes('#shorts')||title.includes(' shorts');player.classList.toggle('is-vertical',portrait);if(player.open){wireFrameAction();enableYoutubeApi()}else portraitNext=false}
  const observer=new MutationObserver(mutations=>{for(const m of mutations){m.addedNodes.forEach(n=>{if(n.nodeType===1)scanThumbs(n)})}scanThumbs();syncPlayer()});
  observer.observe(document.body,{childList:true,subtree:true});
  player?.addEventListener('close',()=>{player.classList.remove('is-vertical');portraitNext=false;latestTime=0;currentFrame=null});
  scanThumbs();
})();
